### ISSUE TITLE
dotnet-format linter fails to run

### ISSUE THREAD

**Issue by adamralph** [github/super-linter#1024]
## Describe the bug

The `dotnet-format` linter fails to run with:

> Unable to locate MSBuild. Ensure the .NET SDK was installed with the official installer.

[For example](https://github.com/adamralph/bullseye/pull/501/checks?check_run_id=1438930064#step:5:133):

> 2020-11-22 18:22:06 [ERROR]   Found errors in [dotnet-format] linter!
> 2020-11-22 18:22:06 [ERROR]   Error code: 3. Command run:[$  Unable to locate MSBuild. Ensure the .NET SDK was installed with the official installer.]

## Expected behavior

The `dotnet-format` linter runs.

## Steps to Reproduce

This is the GH actions file I'm using:

```yaml
on:
  push:
    branches: [master]
  pull_request:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - run: dotnet --info
      - uses: actions/checkout@v2
      - uses: github/super-linter@v3
        env:
          FILTER_REGEX_EXCLUDE: \bLICENSE$|\w*\.sln$|\blog\.txt$
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SHFMT: false
          VALIDATE_EDITORCONFIG: false
```

## Logs

https://github.com/adamralph/bullseye/pull/501/checks?check_run_id=1438930064
