### ISSUE TITLE
Python: Inconsistent lint rules for multiline import.

### ISSUE THREAD

**Issue by kmarilleau** [github/super-linter#1050]
## Describe the bug

Isort and Black doesn't expect the same format result.

Super-Linter Action (is default):
```yaml
      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Example Code:
```python
from src.post_codecs import ContentFormats, Post, PostCodec, PostDecodeError, PostPublisher
```

Super Linter Expected Code for Isort:
```python
from src.post_codecs import (ContentFormats, Post, PostCodec, PostDecodeError,
                             PostPublisher)
```

Super Linter Expected Code for Black:
```python
from src.post_codecs import (
    ContentFormats,
    Post,
    PostCodec,
    PostDecodeError,
    PostPublisher,
)
```

## Suggestion

Isort with these custom rules fix the issue:
```toml
# pyproject.toml
[tool.isort]
multi_line_output = 3 # https://pycqa.github.io/isort/#multi-line-output-modes
include_trailing_comma = true # necessary because black expect the trailing comma.
```
