### ISSUE TITLE
Failed to cleanup volumes

### ISSUE THREAD

**Issue by KineticTheory** [github/super-linter#1180]
## Describe the bug

* I'm using super-linter  in stand-alone mode with gitlab CI CD.  For the most part this works very well.  However at the very end of the CI, it returns a non-zero exit code:
```console
2021-02-02 21:58:03 [INFO]   ----------------------------------------------
2021-02-02 21:58:03 [INFO]   The script has completed
2021-02-02 21:58:03 [INFO]   ----------------------------------------------
2021-02-02 21:58:03 [INFO]   ----------------------------------------------
2021-02-02 21:58:03 [NOTICE]   All file(s) linted successfully with no errors detected
2021-02-02 21:58:03 [INFO]   ----------------------------------------------
ERROR: Failed to cleanup volumes
Job succeeded
```

## Expected behavior

* I'm not sure how to triage this issue and I am looking for suggestions.

## Steps to Reproduce

My `.gitlab.yaml` looks something like this:

```yaml
superlinter:
  image: github/super-linter:latest
  script: [ "true" ]
  only:
    - merge_requests
  variables:
    RUN_LOCAL: "true"
    DEFAULT_WORKSPACE: $CI_PROJECT_DIR
    ANSIBLE_DIRECTORY: $CI_PROJECT_PATH
    LINTER_RULES_PATH: $CI_PROJECT_PATH/.github/linters
    DEFAULT_BRANCH: $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    ERROR_ON_MISSING_EXEC_BIT: "true"
    FILTER_REGEX_EXCLUDE: (.*[.]cc$|/test/)
    PYTHON_FLAKE8_CONFIG_FILE: .flake8
    SUPPRESS_POSSUM: "true"
    VALIDATE_ALL_CODEBASE: "false"
    VALIDATE_BASH: "true"
    VALIDATE_BASH_EXEC: "true"
    VALIDATE_DOCKERFILE: "true"
    VALIDATE_ENV: "true"
    VALIDATE_HTML: "true"
    VALIDATE_JSON: "true"
    VALIDATE_LATEX: "true"
    VALIDATE_LUA: "true"
    VALIDATE_MARKDOWN: "true"
    VALIDATE_PERL: "true"
    VALIDATE_PYTHON: "true"
    VALIDATE_PYTHON_FLAKE8: "true"
    VALIDATE_POWERSHELL: "true"
    VALIDATE_RUBY: "true"
    VALIDATE_SHELL_SHFMT: "true"
    VALIDATE_XML: "true"
    VALIDATE_YAML: "true"
```

## Logs

* I'm not sure how to get to these from my CI system.
