### ISSUE TITLE
Pulling in code history and branches

### ISSUE THREAD

**Issue by avastamin** [github/super-linter#1319]
I have github actions on my react app. I am getting the following errors:

```
Pulling in code history and branches...
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

2021-03-07 22:56:22 [INFO]   Failed to switch to master branch to get files changed!
2021-03-07 22:56:22 [FATAL]   [error: Your local changes to the following files would be overwritten by checkout:
	client/package-lock.json
Please commit your changes or stash them before you switch branches.
Aborting]
```
Settings of the app:
```
name: Lint

on:
  push:
    branches: [master]
  pull_request:
    branches-ignore: []

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      ##########################
      # Clean Workspace #
      ##########################
      - name: Clean Workspace
        uses: AutoModality/action-clean@v1.1.0

      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: npm install
        run: cd client/ && npm i --ignore-scripts

      - name: Super-Linter-on-Client
        uses: docker://ghcr.io/github/super-linter:latest
        env:
          ACTIONS_RUNNER_DEBUG: true
          ERROR_ON_MISSING_EXEC_BIT: true
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: ${{ github.base_ref }}
```
Seeking help from experts about my issues.
