### ISSUE TITLE
Update jspcd to fix naughty strings errors

### ISSUE THREAD

**Issue by snowe2010** [github/super-linter#1335]
## Describe the bug

Bug was https://github.com/kucherenko/jscpd/issues/427, but was fixed in `jscpd@3.3.25`

## Expected behavior
Details are in the linked issue, but essentially jspcd would fail to lint certain naughty strings. 

## Additional context

super-linter just needs to update to the newest jscpd version to fix the issue.

**Comment by snowe2010** [comment]
@GaboFDC seems the bot is still acting up.

**Comment by GaboFDC** [comment]
Jscpd should be up to date. Can you check? And specify what version and build of super linter are you using if you still the the issue?

**Comment by snowe2010** [comment]
Still seeing it on my repo, just ran this build. https://github.com/snowe2010/pretty-print/pull/56/checks?check_run_id=2072748513

Just using 

```yaml
name: Linter

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: .*gradle/.*
          VALIDATE_JAVA: false
          VALIDATE_KOTLIN: false
          VALIDATE_BASH: false
```

https://github.com/snowe2010/pretty-print/blob/124d3a945d5bb1855f84f963f57099ddcdf1b742/.github/workflows/linter.yml
