### ISSUE TITLE
no merge base even with fetch-depth: 0

### ISSUE THREAD

**Issue by xibz** [github/super-linter#1407]
## Describe the bug

I just randomly started getting the `no merge base` error

Here is my config
```yaml
name: Lint Code Base

on: [pull_request]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check Fixups
        uses: 13rac1/block-fixup-merge-action@v2.0.0
      - name: Run linter
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: "Assets/RealToon/*|Assets/Mirror/*|Assets/Tests/*|Assets/Plugins/*"
```

## Expected behavior

Expected it to run the linter.

## Steps to Reproduce

I even confirmed this with an old PR that ran the linter previously and worked. So same commits and everything and just started failing. So no idea what's going on.
