### ISSUE TITLE
Failed to find [coffeelint] in system

### ISSUE THREAD

**Issue by reggieoswald-ads** [github/super-linter#1432]
I'm trying to run golangci-lint in .github/workflows .yaml config 
One of my steps: 
```
 name: lint
 uses: github/super-linter@v3
 env:
    VALIDATE_GO: true
``` 

[golangci-lint/lint] ⭐  Run lint
[golangci-lint/lint]   ☁  git clone 'https://github.com/github/super-linter' # ref=v3
[golangci-lint/lint]   🐳  docker run image=ghcr.io/github/super-linter:v3.15.5 platform=linux/amd64 entrypoint=[] cmd=[]
| 2021-04-06 10:59:56 [FATAL]   Failed to find [coffeelint] in system!
[golangci-lint/lint]   ❌  Failure - lint

`VALIDATE_COFFEE: false` not working for me
