### ISSUE TITLE
Support non-master default branches

### ISSUE THREAD

**Issue by jdyke** [github/super-linter#145]
**Is your feature request related to a problem? Please describe.**
When setting up the linter to run as a github action, it is looking for the `master` branch but ours is named `main`. Fails with error:

```
Failed to switch to master branch to get files changed!
ERROR:[error: pathspec 'master' did not match any file(s) known to git]
```

**Describe the solution you'd like**
An environment variable could be used to input the name of the `default` branch if it is not named `master`.

**Comment by Hanse00** [comment]
@admiralAwkbar I'd like to work on this one, seems like a no brainer idea (And like 10 lines of code)

**Comment by admiralAwkbar** [comment]
@Hanse00 make it so...

**Comment by drewish** [comment]
#152 was merged so seems like this could be closed.

**Comment by jdyke** [comment]
Let me take a look. I tried earlier today and it was still failing even w/ the env var set:

```
  env:
    VALIDATE_ALL_CODEBASE: false
    VALIDATE_PYTHON: true
    DEFAULT_BRANCH: main
```

`/usr/bin/docker run --name githubsuperlinterv200_ef3398 --label 3888d3 --workdir /github/workspace --rm -e VALIDATE_ALL_CODEBASE -e VALIDATE_PYTHON -e DEFAULT_BRANCH`

**Comment by jdyke** [comment]
Looks like #160 is what merged this code into `master` 

I just failed again - is anyone able to get this working? Here is my linter.yml

```
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore:
      - 'main'

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: docker://github/super-linter:v2.0.0
        env:
          DEFAULT_BRANCH: 'main'
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PYTHON: true 

```
