### ISSUE TITLE
Azure Pipelines and configuration (.jsonc > .yml) Rules MD013 & MD033

### ISSUE THREAD

**Issue by tallguyjenks** [github/super-linter#1581]
So I spent a couple days banging my head against my monitor trying to get this to work, and FINALLY I got the docker image to respect my configs.

Here's the `job.yaml` file I have in azure pipelines:

```yaml
trigger:
- '*'

jobs:
  - job: super_linter
    pool:
      vmImage: 'ubuntu-20.04'
    steps:
    - script: docker pull github/super-linter:latest
      displayName: Pull GitHub Super-Linter image
    - script: >-
        docker run \
          -e IGNORE_GITIGNORED_FILES=true \
          -e MARKDOWN_CONFIG_FILE=.markdownlint.jsonc \
          -e LOG_LEVEL=WARN \
          -e RUN_LOCAL=true \
          -v $(System.DefaultWorkingDirectory):/tmp/lint github/super-linter
      displayName: 'Run GitHub Super-Linter'
```

I finally figured out that the image does not respect the `MARKDOWN_CONFIG_FILE` if it's a YAML file.

I messed with:

- the path `.github/linters`
- the file extension `.yml` `.yaml`
- file name `markdown-lint` `markdownlint`
- I passed the explicit variables to the image for the config file name and the path to be the root of the doc based on all the issues I read on the repo

I've literally been scouring the web for everything on this issue since 8 this morning and all it took was making the config file a `.json` or `.jsonc` file.

then no matter what I do with file placement, or referencing it works as intended and ignored the critical things I wanted ignored.

I don't know why, but the issue is now solved for me, but for Azure pipelines for markdown lint it wouldnt respect my rule exceptions for `MD013` to be `false` and `MD033` to respect `["br","u","sub","sup","mark"]` but once I just shifted it all to `.markdownlint.jsonc` with this interior contents:

```jsonc
{ // Example markdownlint JSON(C) configuration with all properties set to their default value
    "default": true, // Default state for all rules
    "extends": null, // Path to configuration file to extend
    "MD001": true, // MD001/heading-increment/header-increment - Heading levels should only increment by one level at a time
    "MD002": { "level": 1 },// MD002/first-heading-h1/first-header-h1 - First heading should be a top-level heading
    "MD003": { "style": "atx" }, // MD003/heading-style/header-style - Heading style
    "MD004": { "style": "dash" }, // MD004/ul-style - Unordered list style
    "MD005": true, // MD005/list-indent - Inconsistent indentation for list items at the same level
    "MD006": true, // MD006/ul-start-left - Consider starting bulleted lists at the beginning of the line
    "MD007": { "indent": 2, "start_indented": false }, // MD007/ul-indent - Unordered list indentation
    "MD009": { "br_spaces": 2, "list_item_empty_lines": false, "strict": false }, // MD009/no-trailing-spaces - Trailing spaces
    "MD010": { "code_blocks": true }, // MD010/no-hard-tabs - Hard tabs
    "MD011": true, // MD011/no-reversed-links - Reversed link syntax
    "MD012": { "maximum": 1 },  // MD012/no-multiple-blanks - Multiple consecutive blank lines
    "MD013": false, // MD013/line-length - Line length
    "MD014": true, // MD014/commands-show-output - Dollar signs used before commands without showing output
    "MD018": true, // MD018/no-missing-space-atx - No space after hash on atx style heading
    "MD019": true, // MD019/no-multiple-space-atx - Multiple spaces after hash on atx style heading
    "MD020": true, // MD020/no-missing-space-closed-atx - No space inside hashes on closed atx style heading
    "MD021": true, // MD021/no-multiple-space-closed-atx - Multiple spaces inside hashes on closed atx style heading
    "MD022": { "lines_above": 1, "lines_below": 1 }, // MD022/blanks-around-headings/blanks-around-headers - Headings should be surrounded by blank lines
    "MD023": true, // MD023/heading-start-left/header-start-left - Headings must start at the beginning of the line
    "MD024": { "allow_different_nesting": false, "siblings_only": false }, // MD024/no-duplicate-heading/no-duplicate-header - Multiple headings with the same content
    "MD025": { "level": 1, "front_matter_title": "^\\s*title\\s*[:=]" }, // MD025/single-title/single-h1 - Multiple top-level headings in the same document
    "MD026": { "punctuation": ".,;:!。，；：！" }, // MD026/no-trailing-punctuation - Trailing punctuation in heading
    "MD027": true, // MD027/no-multiple-space-blockquote - Multiple spaces after blockquote symbol
    "MD028": true, // MD028/no-blanks-blockquote - Blank line inside blockquote
    "MD029": { "style": "one_or_ordered" }, // MD029/ol-prefix - Ordered list item prefix
    "MD030": { "ul_single": 1, "ol_single": 1, "ul_multi": 1, "ol_multi": 1 }, // MD030/list-marker-space - Spaces after list markers
    "MD031": { "list_items": true }, // MD031/blanks-around-fences - Fenced code blocks should be surrounded by blank lines
    "MD032": true, // MD032/blanks-around-lists - Lists should be surrounded by blank lines
    "MD033": { "allowed_elements": ["br","u","sub","sup","mark"] }, // MD033/no-inline-html - Inline HTML
    "MD034": true, // MD034/no-bare-urls - Bare URL used
    "MD035": { "style": "---" }, // MD035/hr-style - Horizontal rule style
    "MD036": { "punctuation": ".,;:!?。，；：！？" }, // MD036/no-emphasis-as-heading/no-emphasis-as-header - Emphasis used instead of a heading
    "MD037": true, // MD037/no-space-in-emphasis - Spaces inside emphasis markers
    "MD038": true, // MD038/no-space-in-code - Spaces inside code span elements
    "MD039": true, // MD039/no-space-in-links - Spaces inside link text
    "MD040": true, // MD040/fenced-code-language - Fenced code blocks should have a language specified
    "MD041": { "level": 1, "front_matter_title": "^\\s*title\\s*[:=]" }, // MD041/first-line-heading/first-line-h1 - First line in a file should be a top-level heading
    "MD042": true, // MD042/no-empty-links - No empty links
    "MD043": false, // MD043/required-headings/required-headers - Required heading structure
    "MD044": { "names": [], "code_blocks": false }, // MD044/proper-names - Proper names should have the correct capitalization
    "MD045": true, // MD045/no-alt-text - Images should have alternate text (alt text)
    "MD046": { "style": "fenced" }, // MD046/code-block-style - Code block style
    "MD047": true, // MD047/single-trailing-newline - Files should end with a single newline character
    "MD048": { "style": "backtick" } // MD048/code-fence-style - Code fence style
}
```

and now it works perfectly as expected.

sorry for the brain dump, just thought it may be useful for others when searching for my issue and maybe a documentation addendum to use `json` configs when running through azure and not github

relevant links/sources/articles used in my insanity to work on this

- https://github.com/github/super-linter/blob/master/README.md#Environment-variables
- https://www.meziantou.net/running-github-super-linter-in-azure-pipelines.htm
- https://blog.tyang.org/2020/06/27/use-github-super-linter-in-azure-pipelines/
- https://docs.docker.com/engine/reference/commandline/run/

**Comment by admiralAwkbar** [comment]
@tallguyjenks This is really interesting!

I looked through the code to make sure I didn't have a typo that was causing this... But it does seem to be an issue from the linter and not our wrapper of it...

I'm wondering if it was a specific version of `markdownlint`  and were passed that version now... We have seen some small issues in a few linters and usually, our base tests catch the main breaks.

Thanks for all the documentation on this!

**Comment by tallguyjenks** [comment]
@admiralAwkbar Glad to be of service! It was a tough debug session but the VSCode extension my team uses, the `*.yml` file works for the local linter, but when also fed to the Job in Azure DevOps it only respected the `*.json` or `*.jsonc` files so I just wrote the settings in `.vscode/settings.json` and duplicated to the config file for the job. 

I'm a balder but more enlightened man now.

**Comment by smholvoet** [comment]
Running into a similar issue, was hoping switching to `.json` from `.yml` would solve my issue but it seems like it keeps searching in the wrong directory. Frustrating as Super Linter runs just fine locally but I keep on having issue with this within Azure DevOps.

```powershell
2022-06-14 11:29:29 [DEBUG]   Checking if the user-provided:[/home/vsts/work/1/s/docs/.markdownlint.jsonc] and exists at:[/tmp/lint/.github/linters//home/vsts/work/1/s/docs/.markdownlint.jsonc]
2022-06-14 11:29:29 [DEBUG]     -> Codebase does NOT have file:[/tmp/lint/.github/linters//home/vsts/work/1/s/docs/.markdownlint.jsonc].
2022-06-14 11:29:29 [DEBUG]     -> Codebase does NOT have file:[/tmp/lint/.github/linters//home/vsts/work/1/s/docs/.markdownlint.jsonc], nor the file:[], using Default rules at:[/action/lib/.automation//home/vsts/work/1/s/docs/.markdownlint.jsonc]
2022-06-14 11:29:29 [DEBUG]     -> Language rules file variable (MARKDOWN_LINTER_RULES) value is:[/action/lib/.automation//home/vsts/work/1/s/docs/.markdownlint.jsonc]
2022-06-14 11:29:29 [FATAL]     -> MARKDOWN_LINTER_RULES rules file (/action/lib/.automation//home/vsts/work/1/s/docs/.markdownlint.jsonc) doesn't exist. Terminating...
##[error]Bash exited with code '1'.
```

Looking at `[/tmp/lint/.github/linters//home/vsts/work/1/s/docs/.markdownlint.jsonc]` it seems to append the config file to the volume which gets mounted to the container:

- My config file is located at: `docs/.markdownlint.jsonc`
- Directory which should be linted: `docs`
- `/home/vsts/work/1/s` = mapped from `$(System.DefaultWorkingDirectory`) or `$PWD` (both probably work)

But for some reason it combines everything and ends up with `/tmp/lint/.github/linters//home/vsts/work/1/s/docs/.markdownlint.jsonc` and `(/action/lib/.automation//home/vsts/work/1/s/docs/.markdownlint.jsonc` a bit later🙈

Does this look familiar to you @tallguyjenks?

**Comment by tallguyjenks** [comment]
@smholvoet if you look at my code above, i have an additional command after the `-v` flag:

`-v $(System.DefaultWorkingDirectory):/tmp/lint github/super-linter`

not really sure what's going on, on your end

my configs that are getting picked up by the container live in the repo at this location for instance:

`.github/linters/.markdownlint.jsonc`

**Comment by gigabytte** [comment]
@smholvoet did you ever find a solution to the appending path issue?

**Comment by smholvoet** [comment]
@gigabytte has been quite a while but I did manage to get this working.

I ended up using a separate docker-compose file instead which then gets called in the pipeline:

**docker-compose-super-linter.yml:**

```yaml
version: '3.9'
services:
    super-linter:
        container_name: super-linter
        image: github/super-linter:slim-v4.10.1
        environment:
            - RUN_LOCAL=true
            - DEFAULT_WORKSPACE=/tmp/lint
            - LINTER_RULES_PATH=.
            - FILTER_REGEX_INCLUDE=.*docs/.*
            - VALIDATE_MARKDOWN=true
            - MARKDOWN_CONFIG_FILE=.markdown-lint.yml
            - NATURAL_LANGUAGE_CONFIG_FILE=.textlintrc
            - CREATE_LOG_FILE=true
        volumes:
            - './:/tmp/lint'
```

**YAML pipeline:**

```
trigger:
- 'none'

jobs:
  - job: lint
    pool:
      vmImage: 'ubuntu-20.04'
    steps:

    - script: docker-compose -f docker-compose-super-linter.yml up
      displayName: 'Run GitHub Super-Linter'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish log file'
      inputs:
        PathtoPublish: 'super-linter.log'
        ArtifactName: 'super-linter-log'
        publishLocation: 'Container'

    # Super-Linter container does not report any exit code, so a dedicated step is needed to break the pipeline if Super-Linter found any issues.
    # Scan the log file to find the outcome of the Super-Linter run.
    - task: Bash@3
      displayName: 'Report Super-Linter exit code'
      inputs:
        targetType: 'inline'
        script: |
          LOGFILE=$(System.DefaultWorkingDirectory)/super-linter.log
          LINTERSUCCEEDED=$(tail $LOGFILE | grep -q "FATAL";echo $?)
          if [ $LINTERSUCCEEDED = 1 ]
          then
            echo 'Super-Linter did not report any issues.'
          else
            echo "##vso[task.logissue type=error]Super-Linter found one or more issues."
            exit 1
          fi
```
