### ISSUE TITLE
Slim image is not resolving based on the documentation example

### ISSUE THREAD

**Issue by TomerFi** [github/super-linter#1596]
## Describe the bug

Using the slim image version as documented fails.

## Expected behavior

The slim image should be pulled and invoked.

## Steps to Reproduce

Use the `super-linter` slim image as documented [here](https://github.com/github/super-linter/tree/v4.0.2#slim-image):

```yaml
- name: Lint Code Base
  uses: ghcr.io://github/super-linter@slim-v4
  env:
    VALIDATE_ALL_CODEBASE: false
    DEFAULT_BRANCH: master
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

## Logs

Will throw an error:

```text
Error: Unable to resolve action `ghcr.io:/github@slim-v4`, repository not found
```

## Additional context

I got around this by pulling the docker image manually:

```yaml
uses: docker://ghcr.io/github/super-linter:slim-v4
```
