### ISSUE TITLE
Install what will be used

### ISSUE THREAD

**Issue by mathiasrw** [github/super-linter#166]
**Is your feature request related to a problem? Please describe.**

Please only install aspects that will be used when linting so that we dont spend time on installing things that will never be used. 

**Describe the solution you'd like**

Example: 

If `VALIDATE_RUBY=false` then skip step 7

    Step 7/16 : RUN gem install rubocop:0.74.0 rubocop-rails rubocop-github:0.13.0

**Describe alternatives you've considered**
Spend 4:56 minutes running the linter step on every pull request where most of the time is spent downloading code that will never run

**Additional context**
It does not need to be fanatic, like - if it takes 2 seconds to download jsonlint its not a priority to "limit" from being installed but lot of building minutes spent with unneeded waiting time for the things that take quite a bit of time like ruby and go if you are using only javascript.

**Comment by ahmadnassri** [comment]
came here for this ... while I love _teh internetz_, I don't want it all installed every time the action runs ... especially if we're paying per minute.

great job otherwise! love this!

**Comment by andymantell** [comment]
Maybe as an alternative you could push a built docker image up to GitHub packages and use that? Rather than building the container every time (Which took 5m 22s on the last run I tried).

**Comment by muenchdo** [comment]
Interestingly in the [announcement blog post](https://github.blog/2020-06-18-introducing-github-super-linter-one-linter-to-rule-them-all/), it actually pulls the image instead of building it:

![super-linter-in-action](https://github.blog/wp-content/uploads/2020/06/super-linter-in-action-2.png?resize=1024%2C819?w=1990)

**Comment by italolelis** [comment]
What I'm doing at the moment is pulling the image like this:

```
      - name: Lint Code Base
        uses: docker://github/super-linter:v2.0.0
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_MD: true
          VALIDATE_TERRAFORM: true
          VALIDATE_YAML: false
          VALIDATE_JSON: false
          VALIDATE_PERL: false
          VALIDATE_XML: false
          VALIDATE_BASH: false
          VALIDATE_PYTHON: false
          VALIDATE_RUBY: false
          VALIDATE_COFFEE: false
          VALIDATE_ANSIBLE: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_DOCKER: false
          VALIDATE_GO: false
```

It takes about 40s to pull the image. It's not pretty, but it does the job.
Maybe as a temporary solution if anybody is interested.
