### ISSUE TITLE
Support to specify the docker image used for super-linter

### ISSUE THREAD

**Issue by RobCannon** [github/super-linter#1690]
**Is your feature request related to a problem? Please describe.**
Our action runners run in our internal environment that is prevented from accessing most internet resources.  So, when this action tries to pull the docker image, it fails:

  /bin/docker pull ghcr.io/github/super-linter:v4.0.2
  Error response from daemon: Get ghcr.io/v2/: read tcp 10.111.11.111:34938->140.11.111.11:443: read: connection reset by peer
  Warning: Docker pull failed with exit code 1, back off 8.946 seconds before retry.

**Describe the solution you'd like**
I would like to be able to specify the docker image that is pulled so it can come from our internal container registry.  I imagine this would be an additional environment variable.

**Comment by admiralAwkbar** [comment]
Hey @RobCannon 

This seems to be an issue with a few users who are in their own DMZ area.
Most of them usually fork the repository into their own areas to host externally.

A simple answer would be to pull the major versions into your internal container registry and then call it from there.

I'm not sure how we could add a flag to have it host from a different location as it pulls from the action.yml that has to be published in the GitHub Container Registry, so I don't think we can variable-ize that.

If you have any other ideas I can do to help, let me know :)

**Comment by RobCannon** [comment]
Well, we have private repos only and forking is disabled due to security, so we can only get certain actions from GitHub whitelisted.

But, won't an input variable work?  I can't test this due to the above, but I think it would work:
```
---
name: 'Super-Linter'
author: 'GitHub'
description: 'It is a simple combination of various linters, written in bash, to help validate your source code.'
inputs:
  image:  # id of input
    description: 'The location of the image to pull'
    required: true
    default: 'docker://ghcr.io/github/super-linter:v4.2.2'
runs:
  using: 'docker'
  image: ${{ inputs.image }}
branding:
  icon: 'check-square'
  color: 'white'
# You can view https://github.com/github/super-linter#environment-variables
# to see a comprehensive list of all environment variables that can be passed
```

**Comment by RobCannon** [comment]
@admiralAwkbar Would my suggestion above work?

**Comment by admiralAwkbar** [comment]
@RobCannon 
I will have to test and see if this is feasible... Its an interesting idea and my only fear is that the `actions.yml` is called somewhat outside, so passing variables to it might not work... but I'm going to try :)_

**Comment by admiralAwkbar** [comment]
So it appears i was right on the idea that we cant call variables in the `action.yml` as its not parsed the same as the rest of the action...

## Logs
```bash
Current runner version: '2.278.0'
Operating System
Virtual Environment
GITHUB_TOKEN Permissions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v2'
Download action repository 'github/super-linter@action-support'
Error: github/super-linter/action-support/action.yml (Line: 12, Col: 10):
Error: github/super-linter/action-support/action.yml (Line: 12, Col: 10): Unrecognized named-value: 'inputs'. Located at position 1 within expression: inputs.image
Error: Fail to load github/super-linter/action-support/action.yml
```

I tried to use the file:
```yml
# Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v4.1.0
        uses: github/super-linter@action-support
        env:
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          image: docker://ghcr.io/github/super-linter:slim-latest
```

So it seems the best possible solution for users in this case:
- Download the docker container to your local registry
- update your actions to point tot he local registry

### Example:
```yml
################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        run: path/to-container/in/artifactory
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
