### ISSUE TITLE
How to run clang-format as part of action

### ISSUE THREAD

**Issue by chester-leung** [github/super-linter#1791]
Hi there, I see that you've [included the clang linter as part of release 4.5](https://github.com/github/super-linter/pull/1762). However, my GitHub action doesn't seem to be running it. I've set the `VALIDATE_CLANG_FORMAT` environment variable to `true`, and also have a `.clang-format` file in my project root directory.  My actions YAML file looks like

```
# Runs the Super-Linter action
- name: Run Super-Linter
  uses: github/super-linter@v4.5.0
  env:
     DEFAULT_BRANCH: master

     LINTER_RULES_PATH: /
     VALIDATE_CLANG_FORMAT: true
     VALIDATE_PYTHON_BLACK: true
     PYTHON_BLACK_CONFIG_FILE: pyproject.toml
```

Any hints on how to actually run the clang formatter as part of the action?
