### ISSUE TITLE
Add ReSharper InspectCode

### ISSUE THREAD

**Issue by Kurt-von-Laven** [github/super-linter#1832]
**Is your feature request related to a problem? Please describe.**
ReSharper is one of the premiere, freely available linters for .NET development. There are a number of GitHub Actions that run its [InspectCode](https://www.jetbrains.com/help/resharper/InspectCode.html) tool, but none of them offer one of Super-Linter's killer features: only run on files changed or added in the pull request. This introduces some friction to getting InspectCode running on changed files from a GitHub Action.

**Describe the solution you'd like**
Include ReSharper's InspectCode command-line tool in the Super-Linter.

**Describe alternatives you've considered**
An alternative would be to create a stand-alone GitHub Action that runs InspectCode on changed files.

**Additional context**
InspectCode runs on the entire solution by default, but can be limited to particular files via the `--include` flag.

**Comment by Kurt-von-Laven** [comment]
I figured out how to set this up for us individually, so in case that is helpful to its inclusion in Super-Linter, I'm sharing that here. It basically boils down to installing ReSharper as a .NET tool and then running it. It should be noted that this tool attempts to build the given solution unless passed `--no-build`, which reduces its efficacy.

Create a `.config/dotnet-tools.json` that looks like this by running `dotnet new tool-manifest && dotnet tool install JetBrains.ReSharper.GlobalTools`:
```json
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "jetbrains.resharper.globaltools": {
      "version": "2021.2.0",
      "commands": [
        "jb"
      ]
    }
  }
}
```

Add the following steps to your workflow:

```yaml
      - name: Set up .NET Core SDK.
        uses: actions/setup@v1.8.1
        with:
          dotnet-version: 5.0.9
      - name: Cache NuGet dependencies.
        uses: actions/cache@v2.1.6
         with:
           path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('.config/dotnet-tools.json') }}
      - name: Install the tools listed at .config/dotnet-tools.json.
          run: dotnet tool restore
      - name: Run ReSharper's InspectCode.
        run: dotnet tool run jb inspectcode <path/to/.sln> -o=<path/to/output/file>
```
