### ISSUE TITLE
PR fork is not working

### ISSUE THREAD

**Issue by segraef** [github/super-linter#1897]
I'm not quite sure if I missed it on the documentation somewhere but it seems PRs from forks are not working. 

https://github.com/Azure/Modules/pull/21

```yaml
name: Linter

on: [pull_request]

jobs:
  build:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: docker://ghcr.io/github/super-linter:slim-v4
        # uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_MARKDOWN: false
          VALIDATE_ARM: false
          VALIDATE_JSON: false
          if: ${{ github.event_name == 'pull_request' }}
          DEFAULT_BRANCH: ${{ github.base_ref }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

https://github.com/Azure/Modules/runs/3433440969?check_suite_focus=true

![image](https://user-images.githubusercontent.com/19261257/130975639-cea40b6c-fdbb-40db-b8fb-bafb7192dedd.png)
