### ISSUE TITLE
super-linter is not "linting" created files during GitHub Action run

### ISSUE THREAD

**Issue by ruzickap** [github/super-linter#1924]
## Describe the bug

`super-linter` can not lint the files which are created during running GitHub Action.

## Steps to Reproduce

I have the following GH Action:

```yaml
name: Lint Code Base
on:
  push:

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Extract commands from markdown files
        run: |
          set -eux
          cat > my_test_script.sh << \EOF
          #!/usr/bin/env bash
          echo `date`
          EOF
          
      - name: Lint Code Base
        uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I believe super linter should check the created `my_test_script.sh`, but it ignores this file.
Is there some option which will allow to lint also this new file which is not part of the git repository?

Does `super-linter` only checks the file which are part of the git repository?

My use case is:
* I have a markdown documentation containing multiple bash commands
* I would like to extract them from MD files when running GH Action and let them check by `super-linter`

Thank you...

**Comment by admiralAwkbar** [comment]
@ruzickap 

try to add the following to make sure it call pull the history correctly:

```yml
##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
```
