### ISSUE TITLE
Behavior not supported, please either only include (VALIDATE=true) or exclude (VALIDATE=false) linters, but not both

### ISSUE THREAD

**Issue by raman-nareika** [github/super-linter#1993]
Faced this error after I added `eslintrc.json`.
So, this piece of code is ok

```
uses: github/super-linter@v4.7.2
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          VALIDATE_BASH_EXEC: false
          VALIDATE_JSCPD: false
          VALIDATE_GITHUB_ACTIONS: false
          VALIDATE_TERRAGRUNT: false
          VALIDATE_DOCKERFILE: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
```

but this - not
```
env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          VALIDATE_BASH_EXEC: false
          VALIDATE_JSCPD: false
          VALIDATE_GITHUB_ACTIONS: false
          VALIDATE_TERRAGRUNT: false
          VALIDATE_DOCKERFILE: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}

          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true
```

When I removed almost all variables the error disappeared
```
env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          
          LINTER_RULES_PATH: /
          JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_JAVASCRIPT_ES: true
```

So, each ENV VAR from the list leads to the error:
```
VALIDATE_BASH_EXEC: false
VALIDATE_JSCPD: false
VALIDATE_GITHUB_ACTIONS: false
VALIDATE_TERRAGRUNT: false
VALIDATE_DOCKERFILE: false
VALIDATE_DOCKERFILE_HADOLINT: false
```

Can the broken code be fixed? I mean if it's possible to combine javascript validation with the validations from the list?

**Comment by raman-nareika** [comment]
this config also leads to the error 
```
        uses: github/super-linter@v4.7.2
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_BASH_EXEC: false
          VALIDATE_JSCPD: false
          VALIDATE_GITHUB_ACTIONS: false
          VALIDATE_TERRAGRUNT: false
          VALIDATE_DOCKERFILE: false
          VALIDATE_DOCKERFILE_HADOLINT: false
          JAVASCRIPT_DEFAULT_STYLE: prettier
          VALIDATE_JAVASCRIPT_ES: true
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
```

but this one works:
```
        uses: github/super-linter@v4.7.2
        env:
          VALIDATE_ALL_CODEBASE: false
          JAVASCRIPT_DEFAULT_STYLE: prettier
          VALIDATE_JAVASCRIPT_ES: true
```
