### ISSUE TITLE
uninitialized constant RuboCop::Cop::Performance::Count::SafeMode with default configuration

### ISSUE THREAD

**Issue by minter** [github/super-linter#207]
**Describe the bug**
I created a `.github/workflows/linter.yml` file in my Rails 6.0.3.2 project. I used the boilerplate from the super-linter documentation.

```
---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore:
      - 'main'

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: docker://github/super-linter:v2.1.0
        env:
          VALIDATE_ALL_CODEBASE: true
```

**To Reproduce**
1. Add linter.yml to codebase
2. Create pull request
3. Observe failures in the GitHub Action
4. For every Ruby file in the project, the error is as follows:
```
File:[./app/models/text_message.rb]
ERROR! Found errors in [rubocop] linter!
ERROR:[uninitialized constant RuboCop::Cop::Performance::Count::SafeMode
/usr/lib/ruby/gems/2.5.0/gems/rubocop-performance-1.3.0/lib/rubocop/cop/performance/count.rb:41:in `<class:Count>'
/usr/lib/ruby/gems/2.5.0/gems/rubocop-performance-1.3.0/lib/rubocop/cop/performance/count.rb:40:in `<module:Performance>'
/usr/lib/ruby/gems/2.5.0/gems/rubocop-performance-1.3.0/lib/rubocop/cop/performance/count.rb:5:in `<module:Cop>'
/usr/lib/ruby/gems/2.5.0/gems/rubocop-performance-1.3.0/lib/rubocop/cop/performance/count.rb:4:in `<module:RuboCop>'
/usr/lib/ruby/gems/2.5.0/gems/rubocop-performance-1.3.0/lib/rubocop/cop/performance/count.rb:3:in `<top (required)>'
/usr/lib/ruby/gems/2.5.0/gems/rubocop-performance-1.3.0/lib/rubocop/cop/performance_cops.rb:15:in `require_relative'
/usr/lib/ruby/gems/2.5.0/gems/rubocop-performance-1.3.0/lib/rubocop/cop/performance_cops.rb:15:in `<top (required)>'
/usr/lib/ruby/gems/2.5.0/gems/rubocop-performance-1.3.0/lib/rubocop-performance.rb:11:in `require_relative'
/usr/lib/ruby/gems/2.5.0/gems/rubocop-performance-1.3.0/lib/rubocop-performance.rb:11:in `<top (required)>'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/gems/2.5.0/gems/rubocop-0.85.1/lib/rubocop/config_loader_resolver.rb:15:in `block in resolve_requires'
/usr/lib/ruby/gems/2.5.0/gems/rubocop-0.85.1/lib/rubocop/config_loader_resolver.rb:11:in `each'
/usr/lib/ruby/gems/2.5.0/gems/rubocop-0.85.1/lib/rubocop/config_loader_resolver.rb:11:in `resolve_requires'
/usr/lib/ruby/gems/2.5.0/gems/rubocop-0.85.1/lib/rubocop/config_loader.rb:45:in `load_file'
/usr/lib/ruby/gems/2.5.0/gems/rubocop-0.85.1/lib/rubocop/config_loader_resolver.rb:166:in `block in base_configs'
/usr/lib/ruby/gems/2.5.0/gems/rubocop-0.85.1/lib/rubocop/config_loader_resolver.rb:165:in `map'
/usr/lib/ruby/gems/2.5.0/gems/rubocop-0.85.1/lib/rubocop/config_loader_resolver.rb:165:in `base_configs'
/usr/lib/ruby/gems/2.5.0/gems/rubocop-0.85.1/lib/rubocop/config_loader_resolver.rb:23:in `resolve_inheritance'
/usr/lib/ruby/gems/2.5.0/gems/rubocop-0.85.1/lib/rubocop/config_loader.rb:51:in `load_file'
/usr/lib/ruby/gems/2.5.0/gems/rubocop-0.85.1/lib/rubocop/config_store.rb:23:in `options_config='
/usr/lib/ruby/gems/2.5.0/gems/rubocop-0.85.1/lib/rubocop/cli.rb:88:in `act_on_options'
/usr/lib/ruby/gems/2.5.0/gems/rubocop-0.85.1/lib/rubocop/cli.rb:38:in `run'
/usr/lib/ruby/gems/2.5.0/gems/rubocop-0.85.1/exe/rubocop:13:in `block in <top (required)>'
/usr/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
/usr/lib/ruby/gems/2.5.0/gems/rubocop-0.85.1/exe/rubocop:12:in `<top (required)>'
/usr/bin/rubocop:23:in `load'
/usr/bin/rubocop:23:in `<main>']
```

**Expected behavior**
With a default configuration, the RuboCop linter should successfully lint the code, and not throw an exception.

**Screenshots**
N/A

**Additional context**
Nothing in my code references `SafeMode`

```
WadesDutMacBook~/git/tourney(super-linter↑1|✔) % grep -r SafeMode .
WadesDutMacBook~/git/tourney(super-linter↑1|✔) % 
```
