### ISSUE TITLE
Documentation Unclear about Use for Pull Requests

### ISSUE THREAD

**Issue by prmph** [github/super-linter#223]
This is a request for clarification and also possibly a bug report. My experience trying this action leaves me thinking the docs are unclear about several things. 

This is my .yml:
```
name: Default

on:
  pull_request:

jobs:
  checks:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with: 
          persist-credentials: false

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: Install
        run: npm ci --no-audit --prefer-offline 

      - name: Lint Code Base
        uses: docker://github/super-linter:v2.1.1
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_ANSIBLE: false

      - name: Build
        run: npm run build:js --if-present
```

I got the following error on the "Lint Code Base" step while running it:

```
Gathering user validation information...
- Only validating [new], or [edited] files in code base...
fatal: could not read Username for 'https://github.com': No such device or address
Failed to switch to master branch to get files changed!
ERROR:[error: pathspec 'master' did not match any file(s) known to git]
```

I have enabled this action on **any** pull request. Is this not a supported scenario? The docs are unclear about it. If is is supported, then why it is looking for the _master_ branch? I would have expected that a comparison would be made between the head and base branches (**not necessarily _master_**) of the PR to find the changed files.

Also, even if there is a comparison with master, I'm unclear what the error `fatal: could not read Username for 'https://github.com': No such device or address` means or indicates. We do have a branch named _master_ in our repository.

**Comment by patcon** [comment]
I hit a similar assumption of `bundlewatch` ecosystem, tat proved false. If it's similar, I would assume that `on: push` would work instead of `on: pull_request` (and push should still shows up as a check within PRs)

**Comment by juanvillegas** [comment]
@prmph I believe you need to set the DEFAULT_BRANCH environment variable to whatever the Pull Request target is: `github.base_ref`.
See here: https://help.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context

My doubt is, what should I use when someone opens a Pull Request and then pushes to that PR? In that case, the github.base_ref is null as the event is a push, so how can I get it to lint the diff between the PR's target branch and current branch?

**Comment by zkoppert** [comment]
@prmph Have you gotten a chance to try `on: push` like @patcon suggested?

**Comment by juanvillegas** [comment]
@zkoppert @prmph I solved this using the `types` property set to 'synchronize', like so:

```
on:
  pull_request:
    branches:
      - 'YOUR BRANCH NAME'
    types: ['synchronize']
```

Synchronize seems to include any code changes to the PR, so it triggers the workflow when creating the PR but also when pushing additional commits to it.
