### ISSUE TITLE
Stylelint throws error on files that should be ignored

### ISSUE THREAD

**Issue by oldfcnd** [github/super-linter#2238]
## Describe the bug

I am using super-lint and in the css file validation process I have set it to ignore CSS files in the public folder as they are automatically generated by npm.

I am using the `.stylelintignore` file based exclusion as stated in the [Stylelint official documentation](https://stylelint.io/user-guide/ignore-code/#files-entirely).

The goal is practically achieved but there is still an error being thrown that I am not able to resolve and, it seems to me, it is a bug.

Errors on file lint actually go away (showing that the file `.stylelintignore` is being found).

However, this error is still poping.
```

2021-12-14 13:35:38 [INFO]   File:[/github/workspace/public/css/app.css]
2021-12-14 13:35:39 [ERROR]   Found errors in [stylelint] linter!
2021-12-14 13:35:39 [ERROR]   Error code: 1. Command output:
------
Error: No files matching the pattern "/github/workspace/public/css/app.css" were found.
    at standalone (/node_modules/stylelint/lib/standalone.js:261:43)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

## Expected behavior

That no errors are thrown, as the file scan by stylelint has been set to be ignored.

## Steps to Reproduce

In the case at hand, to ensure that the error had nothing to do with my project settings and as I work primarily with Laravel projects, I did the following to reproduce the problem.

1 - I created a new Laravel project (I think this is irrelevant to the linter process).
2 - Installed the TailwindCss library (I think it's irrelevant to the linter process).
3 - I configured the workflow as follows:

```
name: Lint Code Base

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:

  run-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_PHP_PSALM: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_EXCLUDE: .*vendor/.*
```

4-  I added the `.stylelintignore` file at root of the project with the following structure:
```
/public/css/*.css
/node_modules
/vendor
```

Note.: For test purpose, I tried without and with the slash at the beginning of the path.

## Additional context

I hosted the project on github so the files can be examined, anyway here are some quick links:
1 - Source code: [fcno/test](https://github.com/fcno/test)
2 - [Stylelink trying to lint the file and throwing erros](https://github.com/fcno/test/runs/4520678329?check_suite_focus=true#step:4:64)
