### ISSUE TITLE
Superlinter doesn't pull the remote repo to lint files!

### ISSUE THREAD

**Issue by Sharath52** [github/super-linter#2287]
## Superlinter doesn't pull the remote repo to lint files when raised a PR

Hi, Ive been working on superlinter for couple of weeks, i just found a strange thing thats happening.I have taken the default snippet of the super-linter action where validation_allcodebase is false and I want to just lint the yaml files.But if i change the code directly on master branch its linting the code as expected , but if i raise a pr from another branch with minor changes its not being linted and im getting this error.

```
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

```
.

## Expected behavior

Superlinter should lint without any errors.

## Steps to Reproduce
1. This is my code 
```
name: Lint Code Base

on: 
  pull_request:
    branches: [main]

- name: Lint Code Base
      uses: github/super-linter@v4
      id: linting_codebase
      env:
        VALIDATE_ALL_CODEBASE: false
        DEFAULT_BRANCH: ${{ github.head_ref }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_YAML: true
```

## Logs

![image](https://user-images.githubusercontent.com/47393562/147864561-483e6c4d-72de-4616-bcd4-736e4b437980.png)

## Additional context

 I have followed the official doc itself and not finding solutions for the same.
