### ISSUE TITLE
Add postcss-scss package to support .SCSS in Stylelint's V14

### ISSUE THREAD

**Issue by mutschelknauss** [github/super-linter#2339]
**Is your feature request related to a problem? Please describe.**
With the new V14 release of Stylelint it only supports CSS out of the box. As the migration guide mentions [here](https://github.com/stylelint/stylelint/blob/main/docs/migration-guide/to-14.md), SCSS support was dropped. As such if you want to support SCSS, you need to have access to the postcss-scss syntax (default bundled with the recommended "stylelint-config-standard-scss").

I made a issue with on the Stylelint repo initially, but they mention this is something to be picked up on Super-linters end by adding [postcss-scss](https://github.com/postcss/postcss-scss) as a part of the runtime packages as mentioned [here](https://github.com/stylelint/stylelint/issues/5832#issuecomment-1013242599). 

**Describe the solution you'd like**
Have super-linter and stylelint maintainers align on ways how to support other syntaxes like SCSS for Stylelint. Or if not possible perhaps mention in documentation that only vanilla CSS is supported from V14 onwards when referring to Stylelint. As it was working great in V13.

**Additional context**
I've made a issue on the stylelint repo [here](https://github.com/stylelint/stylelint/issues/5832)
I've made a minimal code testing repo [here](https://github.com/mutschelknauss/lintertest) with an example of the super-linter PR output [here](https://github.com/mutschelknauss/lintertest/runs/4818424661?check_suite_focus=true)

**Comment by admiralAwkbar** [comment]
@lindluni want to take a stab at getting this added to the image?

**Comment by mutschelknauss** [comment]
Thanks for looking into this, much appreciated. 
If I can help testing if this solved the issue on our end by triggering this specific version in super-linter, I would love to help.

Currently with:
```
################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: docker://github/super-linter:v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_CSS: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

I think it still runs a stable release version correct?
