### ISSUE TITLE
Slim version of super-liner action tied to slim-v4 Docker image tag

### ISSUE THREAD

**Issue by ViacheslavKudinov** [github/super-linter#2395]
## Describe the bug

All tags of slim version of action tied to same Docker image tag  `slim-v4`

## Expected behavior

Tag of action `v4.8.5` uses Docker image `ghcr.io/github/super-linter:slim-v4.8.5`

Few examples:
https://github.com/github/super-linter/blob/v4.8.6/slim/action.yml#L7
https://github.com/github/super-linter/blob/v4.8.5/slim/action.yml#L7
https://github.com/github/super-linter/blob/v4.8.4/slim/action.yml#L7
and so on.....

## Steps to Reproduce

1. Set the tag on workflow file eg 
`uses: github/super-linter/slim@v4.8.5`
1. Trigger the build to execute action 
1. Go to the Actions tab
1. Check the logs

## Logs

> 2022-01-27T09:04:31.1172516Z Found online and idle hosted runner in the current repository's enterprise account that matches the required labels: 'ubuntu-20.04'
> 2022-01-27T09:04:31.1754339Z Waiting for a Hosted runner in the 'enterprise' to pick this job...
> 2022-01-27T09:04:31.4440948Z Job is waiting for a hosted runner to come online.
> 2022-01-27T09:04:36.6222694Z Job is about to start running on the hosted runner: GitHub Actions 3 (hosted)
> 2022-01-27T09:04:40.6680853Z Current runner version: '2.286.1'
> 2022-01-27T09:04:40.6709505Z ##[group]Operating System
> 2022-01-27T09:04:40.6710061Z Ubuntu
> 2022-01-27T09:04:40.6710334Z 20.04.3
> .......
> 2022-01-27T09:04:40.7918216Z Getting action download info
> 2022-01-27T09:04:41.3068439Z Download action repository 'actions/checkout@v2' (SHA:ec3a7ce113134d7a93b817d10a8272cb61118579)

> **2022-01-27T09:04:41.6648482Z Download action repository 'github/super-linter@v4.8.5'** (SHA:b8641364ca9a79b3cf07f3c4c59a82709cd39094)
         
> 2022-01-27T09:04:42.2001644Z ##[group]Pull down action image 'ghcr.io/github/super-linter:slim-v4'

> **2022-01-27T09:04:42.2079977Z ##[command]/usr/bin/docker pull ghcr.io/github/super-linter:slim-v4
> 2022-01-27T09:04:42.7776697Z slim-v4: Pulling from github/super-linter**

> 2022-01-27T09:04:42.7823890Z 59bf1c3509f3: Already exists
> .........
> 2022-01-27T09:05:52.3088351Z f411ef8baad9: Pull complete
> 2022-01-27T09:05:52.3135594Z Digest: sha256:1696f83942c3820ebe899a2dedbb357a6d90c7842ea0c40bd50fc63decad9bf9

> **2022-01-27T09:05:52.3157834Z Status: Downloaded newer image for ghcr.io/github/super-linter:slim-v4**

> 2022-01-27T09:05:52.3202372Z ghcr.io/github/super-linter:slim-v4
> 2022-01-27T09:05:52.3213900Z ##[endgroup]
> 2022-01-27T09:05:52.3637182Z ##[group]Run actions/checkout@v2
> 2022-01-27T09:05:52.3637463Z with:
> 2022-01-27T09:05:52.3637706Z   repository: atgse/gitops-helm
> ..........
> 2022-01-27T09:05:53.7020994Z ##[endgroup]
> 2022-01-27T09:05:53.7092567Z [command]/usr/bin/git log -1 --format='%H'
> 2022-01-27T09:05:53.7126983Z 'd509a4f6baeb0d3c49a0d61e2040d7705be500a3'
> 2022-01-27T09:05:53.7330549Z ##[group]Run github/super-linter/slim@v4.8.5
> ...........

## Additional context
<img width="1370" alt="Screenshot 2022-01-27 at 10 16 29" src="https://user-images.githubusercontent.com/56436734/151333606-ed9ca56d-ffc4-4124-b84b-1f22ac070bbf.png">

**Comment by admiralAwkbar** [comment]
Hey @ViacheslavKudinov Thanks for catching this... Need to see what we broke now :)

**Comment by admiralAwkbar** [comment]
@ferrarimarco @lindluni Either of you have a good solution to this? seems we need to figure this out :)

**Comment by lindluni** [comment]
Hi @ViacheslavKudinov 

We just published 4.8.7 that fixes this issue. Once the 4.8.7 jobs finish running in the Actions tab, you will be able to use 4.8.7 and have it reference the correct images.

Thank you for reporting this bug!

**Comment by ViacheslavKudinov** [comment]
Hi,
as we tied to older version (v4.8.5) we switched way how we use action to
```
     - name: "Run validation"
        uses: docker://ghcr.io/github/super-linter:slim-v4.8.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILTER_REGEX_INCLUDE: .*/(devtest|devtest-ocpv4|lab|preprod-ocpv4|prod)/.*
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_KUBERNETES_KUBEVAL: true
          VALIDATE_YAML: true
          KUBERNETES_KUBEVAL_OPTIONS: "--strict --ignore-missing-schemas --openshift --skip-kinds HelmRelease,SealedSecret,RoleBinding,ServiceMonitor,Instance,ProductConfig,ImagePolicy,HelmRepository,Ingress,Kustomization"

``` 
But, anyway thanks for the fix.
We can back to usual way when we are ready.
