### ISSUE TITLE
Permission error on file after TFLINT

### ISSUE THREAD

**Issue by Official-James** [github/super-linter#2433]
## Describe the bug

Once the super-linter (latest) runs a TF scan and we try to run terraform init, we get the following error:
```
Unable to write the module manifest file: open
.terraform/modules/modules.json: permission denied
```
If we use v4.8.5 we do not have the issue. It looks like the latest release is causing this (v4.8.7)

## Expected behavior

When linter runs VALIDATE_TERRAFORM_TFLINT, it should complete and shouldn't cause errors when running terraform init.

## Steps to Reproduce

Workflow steps:

```yml
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@main
        env:
          VALIDATE_TERRAFORM_TFLINT: true

      - uses: hashicorp/setup-terraform@main
        with:
          terraform_version: latest

      - name: Terraform Init
        id: init
        run: terraform init -backend=false
```

## Logs

```
Unable to write the module manifest file: open
.terraform/modules/modules.json: permission denied
```

## Additional context

The error sounds like the file is left open after lint, causing this error (lock file).
