### ISSUE TITLE
Super-Linter Build step feels slow

### ISSUE THREAD

**Issue by dmitri-lerko** [github/super-linter#247]
Hello!

I've eagerly setup Super-Linter and found that it is by far slowest GitHub Action that I run against my PR.

`Build github/super-linter@v2.0.0` step has taken 4m 27s to complete.

My GitHub Action defined as follows:

```yaml
---
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore:
      - 'master'

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: github/super-linter@v2.0.0
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_YAML: true
```

Is there anything that I am doing wrong? 

Are there any suggestions on how I can make it go faster?
