### ISSUE TITLE
Entire codebase is linted for  PR, even though `VALIDATE_ALL_CODEBASE` is set to `false`

### ISSUE THREAD

**Issue by bewuethr** [github/super-linter#2548]
## Description

Setting `VALIDATE_ALL_CODEBASE` to `false` is ignored, and the entire codebase is linted.

## Expected behaviour

When I open a PR where a single file has been edited and `VALIDATE_ALL_CODEBASE` is `false`, I expect only that single file to be linted, not the entire codebase.

I have looked into a few other, similar issues (see *Additional context*) and made sure my issue is different:

- `fetch-depth` on checkout is set to `0` (though I don't think that would be required to determine what files in a PR have changed)
- the default branch is set to `main`, and my PR is into `main`

## Steps to reproduce

I see the issue in this PR: bewuethr/slack-analyzer#92; I ran locally with something like

```sh
gh repo clone bewuethr/slack-analyzer
cd slack-analyzer
git checkout update-linter

# Run with VALIDATE_ALL_CODEBASE=false
docker run \
    -e RUN_LOCAL=true \
    -e ACTIONS_RUNNER_DEBUG=true \
    -e DISABLE_ERRORS=false \
    -e ERROR_ON_MISSING_EXEC_BIT=true \
    -e LINTER_RULES_PATH=. \
    -e MULTI_STATUS=false \
    -e VALIDATE_ALL_CODEBASE=false \
    -v "$PWD":/tmp/lint \
    ghcr.io/github/super-linter:slim-v4.9.0
```

and the logs indicate that `VALIDATE_ALL_CODEBASE` was `true`, but I believe that is due to `RUN_LOCAL` being `true`.

When looking at the logs of the [workflow run](https://github.com/bewuethr/slack-analyzer/actions/runs/1889548097), I see

```txt
Run github/super-linter/slim@v4.9.0
  env:
    GITHUB_TOKEN: ***
    DEFAULT_BRANCH: main
    VALIDATE_ALL_CODEBASE: false
  
    FILTER_REGEX_EXCLUDE: img/.*

[snip]

[INFO]   --------------------------------------------
2022-02-23 20:40:12 [INFO]   Gathering user validation information...
2022-02-23 20:40:12 [INFO]   - Validating ALL files in code base...
```

and then all files being validated.

## Logs

[Logs of the job that should validate just one file, but doesn't](https://github.com/bewuethr/slack-analyzer/runs/5309902415?check_suite_focus=true)

## Additional context

- [Pull request that triggers the workflow](https://github.com/bewuethr/slack-analyzer/pull/92)
- [Relevant workflow file](https://github.com/bewuethr/slack-analyzer/actions/runs/1889548097/workflow)

### Related issues

- #1123: related to default branch; shouldn't apply, as I'm merging into the default branch
- #728: seems to be about *too few* files being linted
- #400: seems to have been about default branch
- #272: was about `VALIDATE_ALL_CODEBASE` set to `true` disabling some linters

**Comment by BretFisher** [comment]
It is weird that your [VALIDATE_ALL_CODEBASE is set to false](https://github.com/bewuethr/slack-analyzer/runs/5309902415?check_suite_focus=true#step:4:5), but later it says [Validating ALL files in code base](https://github.com/bewuethr/slack-analyzer/runs/5309902415?check_suite_focus=true#step:4:5).

I would try to keep it simple for troubleshooting and hardcode VALIDATE_ALL_CODEBASE to false and re-run.  There's also no need, from what I can see, to regex out img or manually enable linters. super-linter only gives specific file types to specific linters, so I don't see those steps saving you anything.

So, try a new commit in basic form and see if you still see it "Validating ALL files in code base":

```yaml
name: Lint code base

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Lint code base
        uses: github/super-linter/slim@v4.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          VALIDATE_ALL_CODEBASE: false
```

BTW once you get it working, I too have it validate everything on push to main, but this is a better way to ensure "true" is returned when it's not a PR:

`VALIDATE_ALL_CODEBASE: ${{ !contains(github.event_name, 'pull_request') }}`

That prints `true` as the ENV value if it's not a pull_request event, otherwise it prints `false`. That is enough, based on your `on:` events.  No need to also check for branch, because that's already controlled by your events at top.
