### ISSUE TITLE
Is there any way to skip a specific module from being linted?

### ISSUE THREAD

**Issue by PranavPurwar** [github/super-linter#2723]
So, I have a specific module that is copied from another project with some modifications. I want to skip that particular module from being linted so that i can focus on issues in my project (copied module is too big)

**Comment by admiralAwkbar** [comment]
@PranavPurwar 
Hey you should be able to use the flag

`FILTER_REGEX_EXCLUDE`

This will use Regular expression defining which files will be excluded from linting (ex: .*src/test.*)

```
################################
# Run Linter against code base #
################################
- name: Lint Code Base
  uses: github/super-linter@v4
  env:
    VALIDATE_ALL_CODEBASE: false
    DEFAULT_BRANCH: master
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }
    FILTER_REGEX_EXCLUDE: /tmp/some/path
```
