### ISSUE TITLE
config file doesn't exist

### ISSUE THREAD

**Issue by Shivansh-yadav13** [github/super-linter#2815]
I'm trying to set up super linter with black but how am I supposed to locate my config file `pyproject.toml` after checkout, it gives

```
2022-04-21 14:36:25 [INFO]   - Validating ALL files in code base...
2022-04-21 14:36:27 [FATAL]     -> PYTHON_BLACK_LINTER_RULES rules file (/action/lib/.automation/pyproject.toml) doesn't exist. Terminating...
```

my YAML file
```
name: build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Run Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: github/super-linter@v4.2.2
        env:
          VALIDATE_PYTHON_BLACK: true
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          PYTHON_BLACK_CONFIG_FILE: pyproject.toml
```

I guess I'm doing something silly but I'm not able to find the answer to this anywhere so at last, I thought of asking it here.
