### ISSUE TITLE
Linter errors for referencing GitHub script action outputs in GitHub workflow

### ISSUE THREAD

**Issue by stuartleeks** [github/super-linter#2816]
## Describe the bug

Running actionlint tests via super-linter against a GitHub workflow that uses the github-script with custom outputs fails linting, but running the latest actionlint directly passes.

## Expected behavior

The latest actionlint is used and the workflow is treated as valid.

## Steps to Reproduce

Add a workflow similar to the following:

```yaml
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      test: ${{ steps.my_script.outputs.test }}
    steps:
      - id: my_script
        name: Check for a command using GitHub script
        uses: actions/github-script@v6
        with:
          script: |
            core.setOutput("test", "wibble");

      - name: Output 
        run: | 
          echo "test : ${{ steps.my_script.outputs.test }}"
```

You can see this passes with the latest actionlinter in [the playground](https://rhysd.github.io/actionlint/#eJyNkMFOwzAQRO/5ipHVA0gk3DiYCxKHcuMTKts1jaGxo+wuFSr9dxwnWBUnTpZ33ow9m6LGKNQ378mSbgD2xPMJTBKpTVkXK5GlPZpZK1ISHoVp4VYPNucziP1I3fC1IzeFkbsV7GYCl0vhC/NrbRH2GtWwToFoBq/x3Hv3gbc0wcClYTBxD6EQD9gGfhGLPy4hTxrGcUiR7g+Be7Htwjx9PlTslAVdb1hTNL6vZsgPTr4jz6+lw42aO6g7qFOw9ujV7WNTOyy/XUDUkLzAnImrUO/6hBKEf+1L/QAB43x8)

But with the latest super-linter, this fails with 

```

.github/workflows/test.yml:6:20: property "test" is not defined in object type {result: string} [expression]
   |
23 |       test: ${{ steps.my_script.outputs.test }}
   |                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

## Additional context

This is released in actionlint 1.6.11 as per https://github.com/rhysd/actionlint/issues/104

The latest main branch of super-linter is configured for 1.6.12, but I can't see a release/image that includes this.

Am I correct that this issue will be fixed in the next release of super-linter? If so, any idea when the next release might be? 😃
