### ISSUE TITLE
Unable to run super-linter from a GitHub Action (error downloading Docker image)

### ISSUE THREAD

**Issue by jlouros** [github/super-linter#2850]
## Describe the bug

Unable to run super-linter from a GitHub Action

## Expected behavior

Should be able to run without a problem

## Steps to Reproduce

Setup GitHub action with super-linter

```yaml
super-linter:
    runs-on: ubuntu-latest
    steps:
      - name: lint code base
        uses: github/super-linter@v4.9.2
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_BASH_EXEC: false
          VALIDATE_JSCPD: false
          VALIDATE_GITHUB_ACTIONS: false
          VALIDATE_TERRAGRUNT: false
          VALIDATE_SQLFLUFF: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_TYPESCRIPT_STANDARD: false
          VALIDATE_JAVASCRIPT_ES: false
          VALIDATE_TYPESCRIPT_ES: false
          VALIDATE_TSX: false
          FILTER_REGEX_EXCLUDE: '.*test/.*.json|.*src/.*.xml|\.github/.*'
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
```

## Logs

![image](https://user-images.githubusercontent.com/587250/165978381-5fc87e2d-2015-48db-82fb-009db65597e8.png)

## Additional context

Error: 'ghcr.io/github/super-linter:v4.9.2' should be either '[path]/Dockerfile' or 'docker://image[:tag]'.
