### ISSUE TITLE
Version / release tagging

### ISSUE THREAD

**Issue by ruzickap** [github/super-linter#295]
Hello.

Would it be possible to do a proper tagging for this project please?

Maybe good starting point is here: [actions/checkout](https://github.com/actions/checkout/tags)
They are using versions like:

* `v2` -> `v2.2.0`
* `v4` -> `v4.1.0`

It would be really handy to use tags like `v2` instead of specifying the exact version only `v2.2.0`:

```yaml
    - uses: docker://github/super-linter:v2
or
    - uses: github/super-linter@v2
```

Thank you...
