### ISSUE TITLE
How do I only lint changed files in Azure Devops Pipeline?

### ISSUE THREAD

**Issue by tim-steinkuhler** [github/super-linter#3140]
Does anyone know how to make the super linter only lint new / changed files in an Azure Devops Pipeline setup?

I've added the `VALIDATE_ALL_CODEBASE=false` flag, but it still lints all files on each pipeline run

```yaml
# run-linter.yml
stages:
  - stage: "linter"
    displayName: "Run linters for python, yaml etc"
    jobs:
      - job: "run_linter"
        displayName: "Run super linter"
        steps:
          # Here, we add github's super-linter to lint all files
          # credits: https://blog.tyang.org/2020/06/27/use-github-super-linter-in-azure-pipelines/
          - script: |
              docker pull github/super-linter:slim-v4.8.4
              docker run -e RUN_LOCAL=true -e VALIDATE_ALL_CODEBASE=false -e VALIDATE_YAML=false -e VALIDATE_PYTHON_ISORT=false -e VALIDATE_GITLEAKS=false -v $(System.DefaultWorkingDirectory):/tmp/lint github/super-linter:slim-v4.8.4
            displayName: "Code Scan using GitHub Super-Linter"
```
