### ISSUE TITLE
Specify python version

### ISSUE THREAD

**Issue by SoumayaMauthoorMOJ** [github/super-linter#3162]
I can specify which python version(s) to use when linting my code with custom Github action:

```
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8,3.9]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Lint Python files with flake8
        run: >
          flake8 .
      - name: Lint YAML files with yamllint
        run: >
          yamllint .
      - name: Check that isort would not make any changes to imports
        run: >
          isort . --check-only --profile black
      - name: Check that Black would not make any changes to python files
        run: >
          black . --check
```

Can I specify the python version(s) with the super-linter Github action?
