### ISSUE TITLE
PSScriptAnalyzer Error: Invoke-ScriptAnalyzer (not recognized)

### ISSUE THREAD

**Issue by krowlandson** [github/super-linter#318]
**Describe the bug**
When running a vanilla implementation of Super-Linter (v3.0.1 / v.3.1.0), we get the following error within the PSScriptAnalyzer tests:

```bash
File:[<redacted>]
Invoke-ScriptAnalyzer: The term 'Invoke-ScriptAnalyzer' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
ERROR! Found errors in [pwsh] linter!
ERROR:[]
```

**To Reproduce**
1. Using Super Linter v3.0.1 / v.3.1.0 in a GitHub Workflow
2. With all default settings (no VAR defined)
3. Against a repository with PowerShell code present
4. See error against ALL detected files

**Expected behavior**
Expect PSScriptAnaylzer tests to run against all PowerShell files and only raise errors detected by linting.

**GitHub Actions YAML**
The below is the YAML file content used to control this GitHub Action:

```yaml
---
name: Super-Linter

on:
  push

jobs:
  super_linter_on_push:
    name: Run GitHub/Super-Linter on Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v2
      - name: Run GitHub/Super-Linter
        uses: docker://github/super-linter:v3.1.0
```

**Additional context**
Seems to work on local machine using same versions.

**Comment by Rubemlrm** [comment]
@krowlandson there is another issue relative to this bug. The issue is the following #279

**Comment by krowlandson** [comment]
Thank you @Rubemlrm - was literally just looking at that issue and was about to post back to say I think this is a duplicate.

Any thoughts on when this will be resolved, and why it doesn't appear to be a problem within a local run?

**Comment by krowlandson** [comment]
Just to add to my findings, I've been experimenting and found that the following works fine on GitHub Actions:

```yaml
---
name: Super-Linter

on:
  push

jobs:
  super_linter_on_push:
    name: Run GitHub/Super-Linter on Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Repository
        uses: actions/checkout@v2
      - name: Run GitHub/Super-Linter
        run: |
          docker run -e RUN_LOCAL=true -v $GITHUB_WORKSPACE:/tmp/lint github/super-linter:v3.1.0
```

I also tried `uses: github/super-linter@v3.1.0` but that fails too, so the issue appears to be in how GitHub Actions sets up the environment when using the `uses: ... ` format.
