### ISSUE TITLE
awk error when using main branch

### ISSUE THREAD

**Issue by jdyke** [github/super-linter#321]
**Describe the bug**
This bug was fixed previously but it appears to have returned. I am seeing an `awk` error when running the super-linter.

```
--------------------------------------------
Gathering user validation information...
- Validating ALL files in code base...
awk: cmd. line:1: Unexpected end of string
```

The linter passes and appears to be checking the code correctly, but this error was due to malformed or missing `{` last time. Here is the previous issue: https://github.com/github/super-linter/issues/145

**To Reproduce**
1. I am using a default branch of `main` and my `linter.yml` looks like:

```
###########################
###########################
## Linter GitHub Actions ##
###########################
###########################
name: Lint Code Base

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore:
      - 'main'

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Lint Code Base
    # Set the agent to run on
    runs-on: ubuntu-latest

    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
        uses: docker://github/super-linter:v3
        env:
          DEFAULT_BRANCH: 'main'
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_PYTHON: true
```
