### ISSUE TITLE
How to include numpy.typing in mypy linter

### ISSUE THREAD

**Issue by bowentan** [github/super-linter#3301]
I am configuring the GitHub action to do mypy linting but with the default configuration, there were two problems occurring.
1. `error: --install-types failed (no mypy cache directory)`. After creating manually `.mypy_cache` before the step of running super-linter, this error disappeared. Is there any other solutions regarding this issue?
2. `.mypy.ini:7: error: Error importing plugin "numpy.typing.mypy_plugin": No module named 'numpy'`. This plugin should work if numpy was installed in the environment where mypy was running. But how can I include additional packages in the super-linter environment?

My current GitHub action configuration is
```
# This workflow executes several linters on changed files based on languages used in your code base whenever
# you push a code or open a pull request.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/github/super-linter
name: Code lint

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
jobs:
    super-lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  # Full git history is needed to get a proper list of changed
                  # files within `super-linter`
                  fetch-depth: 0
            - name: Make cache
              run: |
                  mkdir .mypy_cache  # For "no mypy cache" problem
            - name: Lint
              uses: github/super-linter/slim@v4
              env:
                  VALIDATE_ALL_CODEBASE: true
                  DEFAULT_BRANCH: "main"
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```
and the mypy linter configuration is
```
# Global options:

[mypy]
python_version = 3.9
warn_return_any = True
warn_unused_configs = True
plugins = numpy.typing.mypy_plugin
disallow_untyped_defs = True
```
