### ISSUE TITLE
Work better for forks by updating example yml

### ISSUE THREAD

**Issue by bazzadp** [github/super-linter#340]
At present the [Example Workflow file](https://github.com/github/super-linter/blob/master/README.md#example-connecting-github-action-workflow) works on pushes only and ignores master branch:

```
#############################
# Start the job on all push #
#############################
on:
  push:
    branches-ignore:
      - 'master'
```

If a repo is forked then this potentially leads to missing linting in the following circumstances:

- If the fork does not have Actions enabled (they are not enabled by default) and then they open a pull request.
- if the contributor works on the `master` branch in their fork and then opens a pull request.

As forks are really key to how GitHub works for a lot of projects, and in fact contributions for non-core contributors are probably ones you definitely want to lint this is not great IMHO.

What [we did](https://github.com/HTTPArchive/almanac.httparchive.org/blob/main/.github/workflows/linter.yml), to improve this, was enable it on all `push` and `pull_requests` (including `master`) but put an exception for local pull requests to avoid running twice:

```
name: Lint Code Base
on:
  - push
  - pull_request
jobs:
  lint:
    name: Lint Code Base
    # Skip duplicate job for local branches
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
```

If the repo is forked, and GitHub actions are enabled then linting happens on `push` (good for contributor), and either way it is run again when the `pull_request` is opened (good for maintainers). So linting always happens (where GitHub Actions are enabled) and the results of the linting can be seen in the pull request issue for review before merging. Which is what we want.

The existing use case (linting from branches in the mean repo) still works as the `push` condition still triggers is used. The `if` statement prevents the action running twice when the Pull Request is opened or added to (as that is technically both a `push` and a `pull_request` as I understand it). It does put 2 checks in place in this case (one for the `push` which is run, and one for the `pull_request` which is skipped). A slight UX issue but the important thing is linting is run - and the results of the last `push` run on that branch are shown in the pull request (even if this happened before the pull requests is opened), which is what we want.

One thing to note with removing the ignoring of master branch, is that this means linting happens again when a pull request is merged into `master`. Again a slight inconvenience (or extra check depending how you look at it!) but think that is worth it to handle forks. Could possibly prevent this happening with a more convoluted `if` statement but, as I say, I think it is a good thing to run this extra check so in our repo we're happy to have this.

What's your thoughts on this? Is my understanding correct (I'm not an expert in GitHub Actions so could be wrong here!)? Should we update the example `linter.yml` file in the README.md to suggest this config instead? If so, I'm happy to submit a PR to change this but thought I'd open an issue first to discuss in case this is not wanted or I've got it totally wrong.
