### ISSUE TITLE
.gitleaksignore file not taken into account

### ISSUE THREAD

**Issue by NicolasMassart** [github/super-linter#3407]
## Describe the bug

.gitleaksignore file not taken into account as it should be according to https://github.com/zricethezav/gitleaks#gitleaksignore

## Expected behavior

.gitleaksignore file used to ignore keys (dev keys in my case)

## Steps to Reproduce

- add a secret to a markdown file, for instance an ethereum test private key in a json code block: 

  ```json
  { "privateKey": "8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63" }
  ```

  👆 This is a test key that has been public for ages, don't worry.
- run `gitleaks detect --source . -v` and see the key being detected (something similar to the following):

  ```text
  Finding:     "privateKey": "8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63",
  Secret:      8f2a55949038a9610f50fb23b5883af3b4ecb3c3bb792cbcefbd1542c692be63
  RuleID:      generic-api-key
  Entropy:     3.812446
  File:        docs/index.md
  Line:        85
  Commit:      [commit hash here]
  Author:      [user name here]
  Email:      [user email here]
  Date:        2019-08-05T15:10:56Z
  Fingerprint: 9f067a02a5efa7110da117e80e8ea58d26847e70:docs/index.md:generic-api-key:85
  ```

- copy the fingerprint to a `.gitleaksignore` file at the project root
- run `gitleaks detect --source . -v` again and notice the file was taken in account as the output of the test is:

  ```bash
  % gitleaks detect --source . -v
  
      ○
      │╲
      │ ○
      ○ ░
      ░    gitleaks
  
  6:59PM INF scan completed in 2.38s
  6:59PM INF no leaks found
  ```
- now, push the project to Github with super-linter workflow and see the linter reporting the leak error instead of ignoring it.

**Comment by ferrarimarco** [comment]
@NicolasMassart how do you configure super-linter?

**Comment by NicolasMassart** [comment]
```yml
---
name: Lint Code Base

on: [pull_request]

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Run check
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter/slim@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: ./CI/lint
          MARKDOWN_CONFIG_FILE: .markdown.yml
          LOG_LEVEL: ERROR
          CSS_FILE_NAME: .stylelintrc.yaml
          FILTER_REGEX_EXCLUDE: (/CI/vale/vale_styles/*|LICENSE)
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_PYTHON: false
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_GITLEAKS: false
```
