### ISSUE TITLE
eslint typescript

### ISSUE THREAD

**Issue by lechen26** [github/super-linter#345]
Hi

i have a Node project written in typescript with included .eslintrc.js file that works properly (npm run lint).
i was trying to integrate with super linter, and something isnt working as i expect it to be.

i did the following:
- i've converted my existing .eslintrc.js file to json and copied it to  .github/linters/.eslintrc.json
- i've added the following step to my workflow:
```
- name: Super Linter
        uses: docker://github/super-linter:v3
        env:
          VALIDATE_TYPESCRIPT_STANDARD: false
          TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.json
```
- i've made a change on my sources that contradict my rules on .eslintrc, and make sure npm run lint indeed failed on them.
-when the CI runs i expected to see the same result with the super linter but i'm getting "all files linted successfully".

i've tried without the env at first, also with the original .eslintrc.js file, same resultt.
what am i missing?

thanks!

**Comment by mirrorkeydev** [comment]
The README states: 

_"Note: All the VALIDATE_[LANGUAGE] _variables behave in a specific way. If none of them are passed, then they all default to true. However if any one of the variables are set, we default to leaving any unset variable to false. This means that if you run the linter "out of the box", all languages will be checked. But if you wish to select specific linters, we give you full control to choose which linters are run, and won't run anything unexpected."_

I think what you're missing is setting Typescript eslint support back to true:

```
env:
  VALIDATE_TYPESCRIPT_STANDARD: false
  VALIDATE_TYPESCRIPT_ES: true
  TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.json
```
Without that, it's not trying to lint the TypeScript at all :) Hope this helps somewhat!
