### ISSUE TITLE
Markdownlint is not reusable with custom rules

### ISSUE THREAD

**Issue by framtale** [github/super-linter#3477]
## Describe the bug
I used the markdownlint workflow as part of the super linter in my private repositories. The workflow runs appropriately with a custom set of rules when I use it to lint the local repository. But when I use the workflow as a reusable one, the super linter can't find the rules.json file anymore so the workflow run fails.

## Expected behavior
To lint the local repository, I set the environment variable `LINTER_RULES_PATH` to lookup the custom rules and it works. But when I use the workflow as a reusable one, the env variable is somehow ignored and super linter is looking for the rule in the `/action/lib/.automation/` directory. I played with the scope of the env variable, but I can't observe any different behavior. However, other env variables such as `MARKDOWN_CONFIG_FILE`work properly.

## Steps to Reproduce

1. Create a repository with a workflow called markdownlint.yml. It has the following content:
```yml
name: Markdown Lint

on:
  workflow_call:
    inputs:
      markdown-config-file:
        required: false
        type: string
        default: "markdownlint-default.json"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      # Runs a single command using the runners shell
      - name: Markdown Lint
        # Uses the slim image to speed up build time
        uses: github/super-linter/slim@v4
        env:
          # Only parse new or edited files
          VALIDATE_ALL_CODEBASE: false
          # Just validate for markdon files
          VALIDATE_MARKDOWN: true
          # Path to the file where the custom markdownlint rules are saved
          LINTER_RULES_PATH: /.github/rules/
          MARKDOWN_CONFIG_FILE: ${{ inputs.markdown-config-file }}
          DEFAULT_BRANCH: ${{ env.GITHUB_REF_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
1. Define a custom set of rules in `/.github/rules/markdownlint-default.json`
1. Now go to another repository and call the markdownlint workflow using:
```yml
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  markdownlint:
    uses: YOUR_REPOSITORY/.github/workflows/markdownlint.yml@main
```

## Logs
2022-10-24 09:29:39 [INFO]   ---------------------------------------------
2022-10-24 09:29:39 [INFO]   --- GitHub Actions Multi Language Linter ----
2022-10-24 09:29:39 [INFO]    - Image Creation Date:[2022-10-04T14:29:23Z]
2022-10-24 09:29:39 [INFO]    - Image Revision:[b5715650a7bd14dad5e74e71b7726e50d929903b]
2022-10-24 09:29:39 [INFO]    - Image Version:[b5715650a7bd14dad5e74e71b7726e50d929903b]
2022-10-24 09:29:39 [INFO]   ---------------------------------------------
2022-10-24 09:29:39 [INFO]   ---------------------------------------------
2022-10-24 09:29:39 [INFO]   The Super-Linter source code can be found at:
2022-10-24 09:29:39 [INFO]    - https://github.com/github/super-linter
2022-10-24 09:29:39 [INFO]   ---------------------------------------------
Removing Languages from LANGUAGE_ARRAY for slim image...
found item:[ARM], removing Language...
found item:[CSHARP], removing Language...
found item:[ENV], removing Language...
found item:[POWERSHELL], removing Language...
found item:[RUST_2015], removing Language...
found item:[RUST_2018], removing Language...
found item:[RUST_2021], removing Language...
found item:[RUST_CLIPPY], removing Language...
Removing Linters from LINTER_NAMES_ARRAY for slim image...
found item:[ARM], removing linter...
found item:[CSHARP], removing linter...
found item:[ENV], removing linter...
found item:[POWERSHELL], removing linter...
found item:[RUST_2015], removing linter...
found item:[RUST_2018], removing linter...
found item:[RUST_2021], removing linter...
found item:[RUST_CLIPPY], removing linter...
2022-10-24 09:29:39 [INFO]   --------------------------------------------
2022-10-24 09:29:39 [INFO]   Gathering GitHub information...
2022-10-24 09:29:39 [INFO]   Successfully found:[GITHUB_SHA], value:[42ffb0e8b3f0808a5bf71f8281ec517797cebf70]
2022-10-24 09:29:39 [INFO]   Successfully found:[GITHUB_WORKSPACE], value:[/github/workspace]
2022-10-24 09:29:39 [INFO]   Successfully found:[GITHUB_EVENT_PATH], value:[/github/workflow/event.json]
2022-10-24 09:29:40 [INFO]   Successfully found:[GITHUB_ORG], value:[framtale]
2022-10-24 09:29:40 [INFO]   Successfully found:[GITHUB_REPO], value:[markdownlint_test]
2022-10-24 09:29:40 [INFO]   Successfully found:[GITHUB_TOKEN]
2022-10-24 09:29:40 [INFO]   Successfully found:[GITHUB_REPOSITORY], value:[framtale/markdownlint_test]
2022-10-24 09:29:40 [INFO]   Successfully found:[GITHUB_RUN_ID], value:[3292083195]
2022-10-24 09:29:40 [INFO]   --------------------------------------------
2022-10-24 09:29:40 [INFO]   Gathering user validation information...
2022-10-24 09:29:40 [INFO]   - Only validating [new], or [edited] files in code base...
2022-10-24 09:29:42 [FATAL]     -> MARKDOWN_LINTER_RULES rules file (/action/lib/.automation/markdownlint-default.json) doesn't exist. Terminating...
