### ISSUE TITLE
Eslint custom files not working - Failed to read JSON file at /action/lib/.automation

### ISSUE THREAD

**Issue by jhomarolo** [github/super-linter#371]
**Describe the bug**
I'm using a javascript linter and every time I try to use my own eslintrc file the action returns an error saying it didn't find the file.

When I use my file with a name other than the default (.**eslintrc_ruler.yml** or .**eslintrc_ruler.json**) in the variable **JAVASCRIPT_ES_CONFIG_FILE** it returns that I didn't find it, if I use a file with the default name .eslintrc.yml it doesn't use my file and uses the action default

**To Reproduce**
1. Here is my linter action url: https://github.com/jhomarolo/suma/blob/develop/.github/linters/.eslintrc_ruler.yml
2. Here is my linter files folders: https://github.com/jhomarolo/suma/tree/develop/.github/linters
3. Some error: https://github.com/jhomarolo/suma/pull/4/checks?check_run_id=835465047
4. Some error: https://github.com/jhomarolo/suma/runs/835456769?check_suite_focus=true
5. This action should break, but did not because ignored my lint file: https://github.com/jhomarolo/suma/runs/835439209?check_suite_focus=true

```       
          - name: Lint Code Base
          uses: docker://github/super-linter:v3.2.0
          env:
            VALIDATE_ALL_CODEBASE: true
            LINTER_RULES_PATH: .github/linters
            JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
            VALIDATE_JAVASCRIPT_STANDARD: false
            VALIDATE_JAVASCRIPT_ES: true                       
            DISABLE_ERRORS: false 
```
**Error founded: Failed to read JSON file at /action/lib/.automation/.eslintrc.json:**

**Expected behavior**
The action is ignoring my eslint files to validate them when I use them in standard nomenclature and giving an error when I when I don't use them in standard nomenclature

**Additional context**
I also tried the 3.1v and erros seems persist
