### ISSUE TITLE
Local super linter failing GitHub_action and google_java_format linting, but succeeds in GitHub Action workflow

### ISSUE THREAD

**Issue by dtran920** [github/super-linter#3981]
## Describe the bug

When running the super linter locally, there is a discrepancy between the results compared to running it through GitHub Actions.

For the differences I have seen, with regards to google_java_format listing, they involve same line annotations.
For instance, the following passes both the local and GitHub Action workflow process:

@Autowired WebTestClient webTestClient;

However the following fails the local super listing, but passes the workflow on GitHub:

@Autowired
WebTestClient webTestClient;
The only reason I realized it was the same line annotation that was causing the error was through running my code through a pre-commit hook from https://github.com/macisamuele/language-formatters-pre-commit-hooks which formatted annotations in the same line when they are parameterless and are field variables. Other pre-commit hook formatters I used for google-java-format consider both variations correct and do not necessitate one over the other unlike what the local listing requires.

Regarding the other bug I had found, when listing for GITHUB_ACTIONS, the following is output:

`/usr/bin/shellcheck --norc -f json -x --shell bash -e SC1091,SC2194,SC2050,SC2154,SC2157 -` did not run successfully while checking script at line:23,col:9: /usr/bin/shellcheck was terminated. stderr: ""

for a GitHub Action yaml file that is contains the following steps:

```    
     steps:
      - name: cleanup #https://github.com/actions/checkout/issues/211
        run: |
          sudo chown -R "$USER:$USER" "$GITHUB_WORKSPACE"
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build, Test and Check Code Coverage
        run: |
          ./gradlew clean jacocoTestCoverageVerification
```

I was able to narrow it down to the fact that there are two run: | commands in the script, as it otherwise would be able to lint successfully without error when either the top run, or the bottom run, are removed. Again, this occurs only locally, but with GitHub Action workflow running the super linter, this passes without any errors or warnings at all.

## Expected behavior

Local super linter run should match the results output by GitHub work flow action process. google_java_format linter when ran locally through super linter should not require annotations be on the same line to match action workflow results.

## Steps to Reproduce

Able to be reproduced by creating a java file that has a field variable with an annotation, new line, followed by declaring a a variable like that mentioned in the description of the bug above. Similarly, two run: | causes the local linting issue for GitHub Action listing.

## Logs

GitHub Action linter log:
`/usr/bin/shellcheck --norc -f json -x --shell bash -e SC1091,SC2194,SC2050,SC2154,SC2157 -` did not run successfully while checking script at line:23,col:9: /usr/bin/shellcheck was terminated. stderr: ""

google-java-format log merely displays the existence of an error in a particular java file, but does not have any useful information to point out the exact cause when ran locally.
