### ISSUE TITLE
Adding v5 Tag to repository

### ISSUE THREAD

**Issue by HenryAsa** [github/super-linter#4083]
## Describe the bug

With the release of `v5.0.0`, a "`v5`" tag should be added, but it does not yet exist.

Kind of related to #4082

## Expected behavior

The `v5.0.0` tag exists, but the `v5` tag does not yet exist.  As a result, I cannot automatically reference the latest `v5` version of the code.

## Steps to Reproduce

1. In any `.github/workflows/linter.yml`, running the following code returns an error:

```
jobs:
  build:
    name: Lint Code Base
    runs-on ubuntu-latest
    steps:
      ###########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
         uses: actions/checkout@v3
         with:
           fetch-depth: 0

      ################################
      # Run Linter against code base #
      ################################
      - name: Lint Code Base
         uses: github/super-linter@v5
```

This returns:

> Unable to resolve action `github/super-linter@v5`, repository or version not found
