### ISSUE TITLE
Editorconfig-checker doesn't properly report errors

### ISSUE THREAD

**Issue by ferrarimarco** [github/super-linter#491]
**Describe the bug**
`editorconfig-checker` doesn't properly report errors, when found.

**To Reproduce**

1. Write a malformed file that editorconfig reports
2. Run `super-linter` against the file.

**Expected behavior**
`super-linter` reports errors in the log, but results are not taken into account.

**Screenshots**
Example output:

```shell
File:[/workspace/configuration/ansible/hosts]
ERROR! Found errors in [editorconfig-checker] linter!
ERROR:[./configuration/ansible/hosts:
	2: Wrong amount of left-padding spaces(want multiple of 4)
	4: Wrong amount of left-padding spaces(want multiple of 4)
	6: Wrong amount of left-padding spaces(want multiple of 4)
	8: Wrong amount of left-padding spaces(want multiple of 4)
	11: Wrong amount of left-padding spaces(want multiple of 4)

5 errors found]
ERROR: Linter CMD:[editorconfig-checker /workspace/configuration/ansible/hosts]
```

And finally:

```shell
All file(s) linted successfully with no errors detected
----------------------------------------------
```

**Additional context**

I'm using the editorconfig-checker configuration that ships with super-linter.

Here's my editorconfig configuration, for reference:

```ini
# EditorConfig: http://EditorConfig.org
root = false

# Unix-style newlines at the bottom of every file
[*]
end_of_line = lf
charset = utf-8

# Tab indentation
indent_style = space
indent_size = 4

# Make sure every file has a blank line at the end
insert_final_newline = true

# Remove any whitespace characters preceding newline characters
trim_trailing_whitespace = true

# Give operators breathing room, but not brackets
spaces_around_operators = true
spaces_around_brackets = false

[*.{yml,yaml}]
indent_style = space
indent_size = 2
```

**Comment by ferrarimarco** [comment]
Some interesting points.

- There's nothing special about how you [call `editorconfig-checker`](https://github.com/github/super-linter/blob/master/lib/linter.sh#L1292):

```shell
########################
# EDITORCONFIG LINTING #
########################
if [ "${VALIDATE_EDITORCONFIG}" == "true" ]; then
  ####################################
  # Lint the files with editorconfig #
  ####################################
  # LintCodebase "FILE_TYPE" "LINTER_NAME" "LINTER_CMD" "FILE_TYPES_REGEX" "FILE_ARRAY"
  LintCodebase "EDITORCONFIG" "editorconfig-checker" "editorconfig-checker" "^.*$" "${FILE_ARRAY_ENV[@]}"
fi
```

Maybe the tool is not correctly reporting the exit code?

**Comment by nemchik** [comment]
I'm able to reproduce. I'll see what i can figure out.

**Comment by kirintwn** [comment]
I'm able to reproduce, `yamllint` seems doesn't properly report errors too.

**Comment by ferrarimarco** [comment]
For me, `yamllint` worked. I used it to validate my reasoning 😄 

What did you try @kirintwn ?

**Comment by kirintwn** [comment]
I'm using `circleci` to run super linter with the following config with no custom lint config:
```
version: 2
jobs:
  test-github-super-linter:
    working_directory: ~/main
    docker:
      - image: github/super-linter:latest
    environment:
      RUN_LOCAL: "true"
      DEFAULT_WORKSPACE: "/root/main"
      VALIDATE_ALL_CODEBASE: "true"
      VALIDATE_CLOUDFORMATION: "true"
      VALIDATE_DOCKER: "true"
      VALIDATE_EDITORCONFIG: "true"
      VALIDATE_JSON: "true"
      VALIDATE_MD: "true"
      VALIDATE_YAML: "true"
    steps:
      - checkout:
          path: ~/main
      - run:
          name: testing
          command: bash /action/lib/linter.sh
```

Here is part of the output of test:
```
---------------------------
File:[/root/main/deployment/charts/templates/utils/get-data/get-data-cj.yaml]
ERROR! Found errors in [yamllint] linter!
ERROR:[/root/main/deployment/charts/templates/utils/get-data/get-data-cj.yaml
  7:14      warning  too many spaces inside braces  (braces)
  27:33     warning  too few spaces after comma  (commas)
  30:13     warning  wrong indentation: expected 14 but found 12  (indentation)
  31:24     warning  too many spaces inside braces  (braces)
  ...
  33:70     warning  too many spaces inside braces  (braces)
  36:1      error    syntax error: could not find expected ':' (syntax)]
ERROR: Linter CMD:[yamllint -c /action/lib/.automation/.yaml-lint.yml /root/main/deployment/charts/templates/utils/get-data/get-data-cj.yaml]
---------------------------
``` 

At the end of testing, it shows no errors detected however:
```
----------------------------------------------
----------------------------------------------
Generated reports:
----------------------------------------------
----------------------------------------------

Reports generated in folder /root/main/super-linter.report

----------------------------------------------
----------------------------------------------
The script has completed
----------------------------------------------
----------------------------------------------

ERROR! Failed to call GitHub Status API!
ERROR:[]
ERROR! Failed to call GitHub Status API!
ERROR:[]
ERROR! Failed to call GitHub Status API!
ERROR:[]
ERROR! Failed to call GitHub Status API!
ERROR:[]

All file(s) linted successfully with no errors detected
----------------------------------------------
```

I have tested it to run locally (with `docker run...`), the output is exactly the same.
And the exit code is still 0.
