### ISSUE TITLE
How can I pass command line arguments to Pylint in Azure DevOps?

### ISSUE THREAD

**Issue by Connell1** [github/super-linter#499]
I am running Super-Linter in an Azure DevOps pipeline and passing the `VALIDATE_PYTHON_PYLINT` environment variable to perform linting using Pylint. When I run the pipeline, I get a load of errors of the form `E0401: Unable to import 'pyspark.sql' (import-error)`. According to the Pylint documentation, module names should be passed as command line arguments. Is there some way I can pass command line args from Super-Linter to Pylint? 

More details is this [Stack Overflow question](https://stackoverflow.com/questions/63176898/super-linter-pass-python-modules-as-arguments-to-pylint-in-azure-devops).

**Comment by admiralAwkbar** [comment]
@Connell1 Hey! thanks for the question...
It seems the option would be to ignore the import errors in the following way:
```python
import someModule # pylint: disable=import-error
```

Or you could ignore them in the `.pylintrc`
```
ignored-modules=module1,module2,...
```

We are currently looking at ways to help users pass more command lines to the linters to help with corner cases and look to have something in the near future.

thanks!

**Comment by GaboFDC** [comment]
Also, you can see related #157 to see how it was solved in GitHub actions, maybe you can extrapolate from there to solve in Azure.

**Comment by Connell1** [comment]
Thanks for the responses. I tried the work around suggested in [#157](https://github.com/github/super-linter/issues/157) but haven't been able to get it working. I have the following code in my pipeline. It still fails to find the python modules so I think my value for the PYTHONPATH variable in the last line is wrong. Can anyone let me know what it should be please?

```
jobs:
  - job: PythonLint
    displayName: Python Lint
    pool:
      vmImage: ubuntu-latest
    steps:
    - script: sudo apt-get install -y --no-install-recommends python3-venv python3-setuptools
      displayName: Install missing python packages

    - script:  |
        python3 -m pip install pipenv
        python3 -m pipenv sync --python 3.6
        python3 -m pipenv install --dev
        python3 -m pipenv lock

      env:
        PIPENV_VENV_IN_PROJECT: 1
      displayName: Install dependencies with pipenv

    - script:  mv .venv /home/vsts/work/_temp/_github_workflow
      displayName: Move the dependencies

    - script: |
        docker pull github/super-linter:latest
        docker run -e RUN_LOCAL=true -e VALIDATE_PYTHON_PYLINT=true -v $(System.DefaultWorkingDirectory)/Azure/Integration:/tmp/lint github/super-linter  -v PYTHONPATH="/github/workflow/.venv/lib/python3.6/site-packages"
      displayName: 'Code Scan using GitHub Super-Linter'
```
