### ISSUE TITLE
multi status not working

### ISSUE THREAD

**Issue by vicyao** [github/super-linter#556]
**Describe the bug**
Setting GITHUB_TOKEN does not seem to then show the statuses of each individual linter for me for pull requests. Explicitly setting MULTI_STATUS to true instead of depending on the default also doesn't change this.

**To Reproduce**

1. Use `docker://github/super-linter:latest` (also tried `docker://github/super-linter:v3.6.0` explicitly) 
2. Open a pull request, push code - whether code passes all checks or not, only the overall status of the full run shows up.

**Expected behavior**
Based on the documentation and #440, I expected to see individual "Linted" statuses. After further testing, I found that the expected behavior happens for code directly pushed to the master branch, but not for pull requests.

**Comment by admiralAwkbar** [comment]
@vicyao I made a small push and hope that fixed it... can you try again with `latest`?

**Comment by admiralAwkbar** [comment]
@vicyao its odd as i wasnt able to directly duplicate the issue but did find missing vars...

**Comment by vicyao** [comment]
@admiralAwkbar Hmmm yeah that's strange; I pulled `latest` but it's still not working - with the PR, this is all I see:
<img width="929" alt="image" src="https://user-images.githubusercontent.com/1190543/90197221-9cdece80-dd93-11ea-9baa-b5ff000310c2.png">

On the master branch though, if I click on the status icon, I do see the individual statuses:
<img width="499" alt="image" src="https://user-images.githubusercontent.com/1190543/90197294-e2030080-dd93-11ea-9482-e5b86c98ce84.png">

**Comment by admiralAwkbar** [comment]
Super odd... I will try to recreate and see if I can find what's causing this issue. Thanks for finding this one

**Comment by vicyao** [comment]
Thanks a lot for looking into it! And in general for developing this - I've been wanting exactly this for all my repos :)

**Comment by admiralAwkbar** [comment]
@vicyao I cant reproduce this...
plase make sure in your branch you have the super-linter and the variable GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} set... its super odd... in the log, do you see errors like failed to call API?

**Comment by vicyao** [comment]
@admiralAwkbar Hmm yeah that's really weird. Yeah I have the GITHUB_TOKEN set everywhere, and no errors in the API on any of the calls.

Not sure if this helps, but just to fiddle around with things, I changed my yml file from only running push on master and any pull_request to the following (within the branch):
```
name: Linter

# Lint pushes to master or pull requests
on: [push, pull_request]

jobs:
  build:
    name: Linter
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Lint code
      uses: docker://github/super-linter:latest
      env:
        MULTI_STATUS: true
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
When linting is triggered twice with a commit to the PR, then multi status does seem to show up for the push triggered event, but not for the PR? 

<img width="863" alt="image" src="https://user-images.githubusercontent.com/1190543/90431646-f9d9cd80-e08e-11ea-8b29-744bdec3662c.png">

**Comment by admiralAwkbar** [comment]
@vicyao I wonder if it's getting lost on the PR sha ref...
if you set to just Push you should not get double jobs and it should be happy? can you try that?

**Comment by vicyao** [comment]
@admiralAwkbar Yup that works! 
I was originally trying to set it so that the linter didn't run twice with pushes to a branch in a PR, but I'm happy just to leave it like this to get the multiple status messages.

**Comment by admiralAwkbar** [comment]
@vicyao thanks for finding this... i will see about a future fix on it!

**Comment by bewuethr** [comment]
FWIW, I see the exact same thing: with triggers set to

```yaml
on:
    push:
      branches:
        - master
    pull_request:
      branches:
        - master
```

I don't have per-language status and don't see failed calls in the logs (see [action run](https://github.com/bewuethr/pandoc-bash-blog/runs/1245673489?check_suite_focus=true)); with triggers set to

```yaml
on:
  push:
```

I get individual status (see [action run](https://github.com/bewuethr/pandoc-bash-blog/runs/1245688506?check_suite_focus=true)).
