### ISSUE TITLE
ENOENT error occurring after defining a stylelint config file with the CSS_FILE_NAME env var

### ISSUE THREAD

**Issue by josephmarino** [github/super-linter#685]
:wave: Hi folks, I think I found a bug. 

**Describe the bug**

When linting CSS code, it looks like super-linter cannot locate a stylelint config file when a config file such as .stylelintrc.yml is defined in the CSS_FILE_NAME environment variable.

**To Reproduce**

1. Create a repo

2. Create a super-linter linter.yml config file in a .github/workflows folder of the repo, and then add the following env vars to the linter.yml file:

```yaml
env:
  VALIDATE_ALL_CODEBASE: true
  CSS_FILE_NAME: .stylelintrc.yml
  VALIDATE_CSS: true
```

3. Create a .stylelintrc.yml file in the root directory of the repo and add the following rules to the file:

```yaml

rules:
  color-no-invalid-hex: true
  function-calc-no-invalid: true
  function-calc-no-unspaced-operator: true
  function-linear-gradient-no-nonstandard-direction: true
  string-no-newline: true
  unit-no-unknown: true
  keyframe-declaration-no-important: true
  block-no-empty: true
  selector-pseudo-class-no-unknown: true

``` 

4. Create a test.css file in the root directory of the repo and add the following CSS code to the file: 

```css

.test {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 12px;
	color: #313131;
}

```

5. Run super-linter

**Expected behavior**

I was expecting super-linter to execute stylelint with the .stylelintrc.yml config file that is located in the repo's root directory after including the following env vars in super-linter's yaml config file:

```yaml 
CSS_FILE_NAME: .stylelintrc.yml
VALIDATE_CSS: true
```

**Screenshots**

Below is a screenshot showing the ENOENT error

![ENOENT-ERROR](https://user-images.githubusercontent.com/6936994/92348883-68b0b200-f0a2-11ea-9bd7-58058c853079.jpg)

**Additional context**

I reproduced this bug in a test repo. Below is a link to the github actions workflow showing the ENOENT error occurring:
https://github.com/josephmarino/super-linter-css-bug/runs/1079743302

Also in this test repo is a workflow that fetches stylelint via npm and then successfully executes stylelint using the .stylelintrc.yml file against the test.css file. The link to that workflow is here: https://github.com/josephmarino/super-linter-css-bug/runs/1079743298?check_suite_focus=true

I hope that this information is helpful.
