### ISSUE TITLE
Exclude .github folder from linting

### ISSUE THREAD

**Issue by MrSquaare** [github/super-linter#726]
Hello,

I've tried to exclude the .github folder from linting but it seems it doesn't work

Here is my workflow config:
```yml
name: Pull Request

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Lint
        uses: github/super-linter@v3
        env:
          FILTER_REGEX_EXCLUDE: .*.github/.*
          VALIDATE_ALL_CODEBASE: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

Thanks!
