### ISSUE TITLE
Protocol Buffer Linter not using GetLinterRules

### ISSUE THREAD

**Issue by eiei0** [github/super-linter#755]
It seems like the same thing that has happened in #524 with PHP is happening to the Protocol Buffers linter. After adding our `.protolint.yml` config to `.github/linters` as described [in the README](https://github.com/github/super-linter#template-rules-files), the workflow logs still show that its referencing the default location. I'm not sure, but I think it should be added [here](https://github.com/github/super-linter/blob/master/lib/linter.sh#L1272).

#### Logs
```
2020-09-18 22:33:44 [ERROR ]   Linter CMD:[protolint lint --config_path /action/lib/.automation/.protolintrc.yml lms/assignments.proto]
```
#### `.github/linters/.protolintrc.yml`
```
# Lint directives.
lint:
  # Linter rules options.
  rules_option:
    max_line_length:
      max_chars: 90
```
#### `.github/workflows/main.yml`
```
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Lint Protos
        uses: github/super-linter@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PROTOBUF: true
```

Am I doing it wrong?
