### ISSUE TITLE
Support JSON Linter with syntax validation

### ISSUE THREAD

**Issue by maxim-lobanov** [github/super-linter#776]
**Is your feature request related to a problem? Please describe.**
Currently, `github/super-linter` uses [jsonlint](https://github.com/zaach/jsonlint) to validate `*.json` files.
The problem is that this linter can't report styling issues.
It can report syntax issues (when JSON is invalid) and can beautify JSON file (that is useless for github/super-linter). 

**Describe the solution you'd like**
It would be great to have JSON linter, that can report styling issues 

**Additional context**
It would be great if JSON linter is able to find and report issues like on picture below:
![image](https://user-images.githubusercontent.com/16715858/94416384-762ff800-0187-11eb-9b27-b67a6f0d47b7.png)

**Comment by admiralAwkbar** [comment]
@maxim-lobanov Do you know of any library we could use that makes this available?
Currently, [jsonlint](https://github.com/zaach/jsonlint) was the only good one available

thanks!

**Comment by maxim-lobanov** [comment]
Unfortunately, I don't know CLI tools that can do that.

Just an option: `eslint` can be configured to use [eslint-plugin-json-format](https://www.npmjs.com/package/eslint-plugin-json-format) plugin. It works perfect for me

**Comment by nantiferov** [comment]
So far I was able to add json formatting lint only with eslint:
```yml
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
      - run: npm install eslint eslint-plugin-json-format
      - run: npx eslint --ext .json .
```
with .eslintrc.json
```json
{
  "plugins": [
    "json-format"
  ]
}
```

@maxim-lobanov  thank you for suggestion 👍
