### ISSUE TITLE
Black linter failing again...

### ISSUE THREAD

**Issue by jeremiahlewis-vw** [github/super-linter#807]
The black linter step is using v19 instead of v20, as can be seen in this line of the Pipfile.lock file. Solution might be to pin the version to at least version 20, or to pin it to v20 to avoid unplanned breaking changes.
https://github.com/github/super-linter/blob/6902cbfd3d6ca9432bcfa450ff91a3f6ca2472e1/dependencies/Pipfile.lock#L67

**Comment by jeremiahlewis-vw** [comment]
Same issue as here: https://github.com/github/super-linter/issues/722

**Comment by jeremiahlewis-vw** [comment]
What about enforcing a minimum version in the Pipfile?

https://github.com/github/super-linter/blob/6902cbfd3d6ca9432bcfa450ff91a3f6ca2472e1/dependencies/Pipfile#L9

->
`black = ">=20"`

**Comment by mamilov** [comment]
Failing for me as well, also using 20.8b1

**Comment by admiralAwkbar** [comment]
@jeremiahlewis-vw Can you pin the version in the pip file so this stops happening? I think that should be a good fix for now and will get you 1 PR closer to hacktoberfest :)

**Comment by jeremiahlewis-vw** [comment]
Would love to contribute, but unfortunately can't do a PR, for reasons. Anyone else down for the PR?

**Comment by admiralAwkbar** [comment]
This was merged and fixed!

**Comment by KSmanis** [comment]
Apparently still relevant:
```shell
$ docker run --entrypoint /usr/bin/env --rm github/super-linter:latest black --version
black, version 19.10b0
```

**Comment by mamilov** [comment]
Just checked as well, it's still the old version in Pipfile.lock. Probably need to upgrade the dependencies...

**Comment by jeremiahlewis-vw** [comment]
Think the issue is conflicting dependency requirements, looks like snakefmt requires the 19.* version of black:

https://github.com/snakemake/snakefmt/blob/master/pyproject.toml

**Comment by KSmanis** [comment]
Unfortunately the underlying problem seems to be conflicting dependencies. As per my [previous comment](https://github.com/github/super-linter/issues/807#issuecomment-717868515):
> Edit: `snakefmt==0.2.3` requires `black >=19.10b0,<20.0`

**Comment by GaboFDC** [comment]
And just to be clear, what is the issue with black 19? why we can't keep it in the version compatible with snakefmt?

**Comment by KSmanis** [comment]
They don't produce identical output, thus leading to the relevant CI check failing if there is a version mismatch between the dev and the CI environments.

**Comment by montyly** [comment]
Would it be somehow possible to overcome this by passing a flag to the super linter?

For example either:
- a generic `FORCE_LATEST`, that would take a list of name, and use the latest version for this tool
- a per tool `FORCE_LATEST_X`, that would force the latest version of the tool

`FORCE_LATEST` might lead to conflicts between tools, but the user can prevent this by running the tools  in separate `steps`, ex:
```
    steps:
      - name: Black
        uses: docker://github/super-linter:v3
        if: always()
        env:
          # Run only black
          VALIDATE_PYTHON_BLACK: true
          FORCE_LATEST_BLACK: true

      - name: Lint everything else
        uses: docker://github/super-linter:v3
        if: always()
        env:
          # run everything except black
          VALIDATE_PYTHON_BLACK: false
```

It seems that we only have this conflict with `skanefmt`/`black` at the moment, but I won't be surprised if similar issues arise with  the add of other linters.
