### ISSUE TITLE
[Noob Q] How do I use FILTER_REGEX_EXCLUDE?

### ISSUE THREAD

**Issue by KineticTheory** [github/super-linter#847]
Can someone provide an example for me wrt `FILTER_REGEX_EXCLUDE?.  I would like to eliminate this warning:
```console
2020-10-13 15:58:15 [WARN  ]   Failed to get filetype for:[src/linear/qrdcmp.hh]!
```

I currently have this in `linter.yml`, but it doesn't eliminate the warning:
```yaml
jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          DEFAULT_BRANCH: develop
          FILTER_REGEX_EXCLUDE: .*/.*.hh
```

Do I need to `.*/.*/.*.hh`?  The regex format isn't exactly what I am used to using.

Thank you!
