### ISSUE TITLE
_LINTER_RULES rules doesn't exist

### ISSUE THREAD

**Issue by pdelre** [github/super-linter#864]
I'm also seeing issues when `MARKDOWN_CONFIG_FILE` is set, it is unable to find the file unless `LINTER_RULES_PATH` is also set.

Doesn't work

```yaml
      - uses: github/super-linter@v3
        env:
          VALIDATE_MARKDOWN: true
          MARKDOWN_CONFIG_FILE: docs/.markdownlint.yml
```

Works

```yaml
      - uses: github/super-linter@v3
        env:
          LINTER_RULES_PATH: '.' # From https://github.com/github/super-linter/pull/859#issuecomment-709625090
          VALIDATE_MARKDOWN: true
          MARKDOWN_CONFIG_FILE: docs/.markdownlint.yml
```

Continued from #858 & #859

> Not sure if it's #854 or #859 but, if you provide, for example, JAVASCRIPT_ES_CONFIG_FILE it still tries to look for it in the DEFAULT_RULES_LOCATION when LINTER_RULES_PATH is not set (so i guess it ignores the default?). When you set LINTER_RULES_PATH it works fine.

_Originally posted by @PhunStyle in https://github.com/github/super-linter/pull/859#issuecomment-709625090_
