### ISSUE TITLE
Kubernetes validation should not fail on CRD's

### ISSUE THREAD

**Issue by pbstriker38** [github/super-linter#891]
Kubeval validation fails when given a K8 configuration with a custom resource definition. The ignore missing schema flag should be used when running `kubeval`.
https://www.kubeval.com/#crds
```
kubeval --ignore-missing-schemas
```

**To Reproduce**
1. Create a file with a CRD
```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: productpage
spec:
  hosts:
  - productpage
  http:
  - route:
    - destination:
        host: productpage
        subset: v1
```

2. Run lint

**Expected behavior**
The file should not be validated since it is an unknown Kubernetes type.

**Screenshots**
![image](https://user-images.githubusercontent.com/5264240/96789809-b3646000-13aa-11eb-9e62-743440f1b3c5.png)
